python-scipy: update to 1.18.0 (#30365)
* build with meson-python

diff --git a/mingw-w64-python-scipy/PKGBUILD b/mingw-w64-python-scipy/PKGBUILD
--- a/mingw-w64-python-scipy/PKGBUILD
+++ b/mingw-w64-python-scipy/PKGBUILD
@@ -4,8 +4,8 @@
 _realname=scipy
 pkgbase=mingw-w64-python-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-python-${_realname}")
-pkgver=1.17.1
-pkgrel=3
+pkgver=1.18.0
+pkgrel=1
 pkgdesc="SciPy is open-source software for mathematics, science, and engineering (mingw-w64)"
 arch=('any')
 mingw_arch=('mingw64' 'ucrt64' 'clang64' 'clangarm64')
@@ -20,8 +20,10 @@ depends=(
   "${MINGW_PACKAGE_PREFIX}-python"
   "${MINGW_PACKAGE_PREFIX}-python-numpy"
   "${MINGW_PACKAGE_PREFIX}-cc-libs"
-  $([[ ${MINGW_PACKAGE_PREFIX} == *-clang-* ]] || echo "${MINGW_PACKAGE_PREFIX}-gcc-libgfortran")
-  "${MINGW_PACKAGE_PREFIX}-openblas")
+  $([[ ${MINGW_PACKAGE_PREFIX} == *-clang-* ]] || echo "${MINGW_PACKAGE_PREFIX}-fc-libs")
+  "${MINGW_PACKAGE_PREFIX}-openblas"
+  # "${MINGW_PACKAGE_PREFIX}-qhull"
+)
 optdepends=(
   "${MINGW_PACKAGE_PREFIX}-python-pillow: for image saving module"
 )
@@ -32,16 +34,19 @@ makedepends=(
   "${MINGW_PACKAGE_PREFIX}-cc"
   "${MINGW_PACKAGE_PREFIX}-fc"
   "${MINGW_PACKAGE_PREFIX}-meson"
+  "${MINGW_PACKAGE_PREFIX}-meson-python"
   "${MINGW_PACKAGE_PREFIX}-ninja"
   "${MINGW_PACKAGE_PREFIX}-pkgconf"
   "${MINGW_PACKAGE_PREFIX}-cython"
   "${MINGW_PACKAGE_PREFIX}-pybind11"
+  "${MINGW_PACKAGE_PREFIX}-python-build"
+  "${MINGW_PACKAGE_PREFIX}-python-installer"
   "${MINGW_PACKAGE_PREFIX}-python-pythran"
 )
 source=("https://pypi.python.org/packages/source/${_realname:0:1}/${_realname}/${_realname}-${pkgver}.tar.gz"
         "001-no-static-linking.patch"
         "002-no-long-double-64.patch")
-sha256sums=('95d8e012d8cb8816c226aef832200b1d45109ed4464303e997c5b13122b297c0'
+sha256sums=('67b2ad2ad54c72ca6d04975a9b2df8c3638c34ddd5b28738e94fc2b57929d378'
             'd418dffecdce7c746d08db5d6301798d6b60444572d85f10789e07995397f2a2'
             '5531a507a0c958687e7476f896d88dbd6f948f121f75da46e2eee31be9f0b8ca')
 
@@ -62,41 +67,20 @@ prepare() {
 }
 
 build() {
-  mkdir -p build-${MSYSTEM} && cd build-${MSYSTEM}
+  cp -r "${_realname}-${pkgver}" "python-build-${MSYSTEM}" && cd "python-build-${MSYSTEM}"
 
-  declare -a _extra_config
-  if check_option "debug" "n"; then
-    _extra_config+=("-Dbuildtype=release")
-  else
-    _extra_config+=("-Dbuildtype=debug")
-  fi
-
-  MSYS2_ARG_CONV_EXCL="--prefix=" \
-    ${MINGW_PREFIX}/bin/meson setup \
-      --prefix="${MINGW_PREFIX}" \
-      --wrap-mode=nodownload \
-      --auto-features=enabled \
-      -Dwarning_level=0 \
-      "${_extra_config[@]}" \
-      ../${_realname}-${pkgver}
-
-  ${MINGW_PREFIX}/bin/meson compile
+  # Currently using system qhull failed with "undefined reference to `qh_memcheck'"
+  python -m build --wheel --skip-dependency-check --no-isolation \
+    # -Csetup-args="-Duse-system-libraries=all"
 }
 
 package() {
-  cd "${srcdir}/build-${MSYSTEM}"
+  cd "${srcdir}/python-build-${MSYSTEM}"
 
-  DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/meson install
-
-  # https://github.com/msys2/MINGW-packages/pull/12386#issuecomment-1201661997
-  _purelib="$(python -c "import sysconfig; print(sysconfig.get_path('purelib'))")"
-  _site_packages="${pkgdir}$(cygpath "${_purelib}")"
-  cp "${srcdir}/${_realname}-${pkgver}/PKG-INFO" "${_site_packages}/${_realname}-${pkgver}.egg-info"
+  MSYS2_ARG_CONV_EXCL="--prefix=" \
+    python -m installer --prefix=${MINGW_PREFIX} --destdir="${pkgdir}" dist/*.whl
 
   find "${pkgdir}${MINGW_PREFIX}" -name '*.dll.a' -delete
-
-  MSYS2_ARG_CONV_EXCL="-p" python -m compileall \
-    -o 0 -o 1 -q -s"${pkgdir}" -p"/" "${pkgdir}${MINGW_PREFIX}/lib/python"*
 
   install -Dm644 "${srcdir}/${_realname}-${pkgver}/LICENSE.txt" \
     "${pkgdir}${MINGW_PREFIX}/share/licenses/python-${_realname}/LICENSE"
