Convert tabs to 2 spaces.
Signed-off-by: ofry <tim4job@bmail.ru>

diff --git a/mingw-w64-bmake/PKGBUILD b/mingw-w64-bmake/PKGBUILD
--- a/mingw-w64-bmake/PKGBUILD
+++ b/mingw-w64-bmake/PKGBUILD
@@ -2,6 +2,7 @@
 # Contributor: Alex Szczuczko <alex at szc dot ca>
 # Contributor: Devin Cofer <ranguvar{AT]archlinux[DOT}us>
 # Contributor: Imanol Celaya <ilcra1989@gmail.com>
+# Windows port: Timofey Denisov <tim4job@bmail.ru>
 
 _realname=bmake
 pkgbase=mingw-w64-${_realname}
@@ -41,33 +42,33 @@ prepare() {
 }
 
 build() {
-	cd "${srcdir}"/bmake
-	export SYSROOTWINDOWSPATH=$(cygpath -w /)
-    aclocal --verbose || die "aclocal failed"
-    autoreconf --verbose || die "autoreconf failed"
-	bash -x ./boot-strap --prefix=${MINGW_PREFIX} op=build
+  cd "${srcdir}"/bmake
+  export SYSROOTWINDOWSPATH=$(cygpath -w /)
+  aclocal --verbose || die "aclocal failed"
+  autoreconf --verbose || die "autoreconf failed"
+  bash -x ./boot-strap --prefix=${MINGW_PREFIX} op=build
 }
 
 # op=build also runs unit tests; thus no check()
 
 package() {
-	cd "${srcdir}"/bmake
+  cd "${srcdir}"/bmake
 
-	export SYSROOTWINDOWSPATH=$(cygpath -w /)
+  export SYSROOTWINDOWSPATH=$(cygpath -w /)
 
-	# Fix directory permissions on install
-	# install -Dm644 "${pkgdir}${MINGW_PREFIX}/bin" "${pkgdir}${MINGW_PREFIX}/share/licenses/$pkgname"
+  # Fix directory permissions on install
+  # install -Dm644 "${pkgdir}${MINGW_PREFIX}/bin" "${pkgdir}${MINGW_PREFIX}/share/licenses/$pkgname"
 
-	bash -x ./boot-strap --install-destdir="${pkgdir}" --prefix=${MINGW_PREFIX} op=install
+  bash -x ./boot-strap --install-destdir="${pkgdir}" --prefix=${MINGW_PREFIX} op=install
 
-	rm -rf "${pkgdir}${MINGW_PREFIX}/share/man/cat1"
-	install -Dm644 bmake.1 "${pkgdir}${MINGW_PREFIX}/share/man/man1/bmake.1"
+  rm -rf "${pkgdir}${MINGW_PREFIX}/share/man/cat1"
+  install -Dm644 bmake.1 "${pkgdir}${MINGW_PREFIX}/share/man/man1/bmake.1"
 
-    mkdir -p "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}"
-	head -n70 main.c > "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
+  mkdir -p "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}"
+  head -n70 main.c > "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
 
-	# install profile script
-    mkdir -p "${pkgdir}${MINGW_PREFIX}"/etc/profile.d
-    echo "export SYSROOTWINDOWSPATH=$(cygpath -w /)" > "${pkgdir}${MINGW_PREFIX}"/etc/profile.d/bmake.sh
-    cp "${pkgdir}${MINGW_PREFIX}"/etc/profile.d/bmake.{sh,zsh}
+  # install profile script
+  mkdir -p "${pkgdir}${MINGW_PREFIX}"/etc/profile.d
+  echo "export SYSROOTWINDOWSPATH=$(cygpath -w /)" > "${pkgdir}${MINGW_PREFIX}"/etc/profile.d/bmake.sh
+  cp "${pkgdir}${MINGW_PREFIX}"/etc/profile.d/bmake.{sh,zsh}
 }
