Rebuild old packages, part 3 (#31050)
* Rebuild old packages, part 3

These packages haven't been rebuilt since 2022-04-01

* cpputest: fix build

* gl2ps: fix build

diff --git a/mingw-w64-cpputest/PKGBUILD b/mingw-w64-cpputest/PKGBUILD
--- a/mingw-w64-cpputest/PKGBUILD
+++ b/mingw-w64-cpputest/PKGBUILD
@@ -4,20 +4,22 @@ _realname=cpputest
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
 pkgver=4.0
-pkgrel=2
+pkgrel=3
 pkgdesc="Unit testing and mocking framework for C and C++ (mingw-w64)"
 url="https://cpputest.github.io/"
 msys2_repository_url='https://github.com/cpputest/cpputest'
 arch=('any')
 mingw_arch=('mingw64' 'ucrt64' 'clang64' 'clangarm64')
 license=('spdx:BSD-3-Clause')
-makedepends=("${MINGW_PACKAGE_PREFIX}-cmake"
-             "${MINGW_PACKAGE_PREFIX}-ninja"
-             "${MINGW_PACKAGE_PREFIX}-cc")
-source=("https://github.com/cpputest/cpputest/releases/download/v${pkgver}/${_realname}-${pkgver}.tar.gz"
+makedepends=(
+  "${MINGW_PACKAGE_PREFIX}-cc"
+  "${MINGW_PACKAGE_PREFIX}-cmake"
+  "${MINGW_PACKAGE_PREFIX}-ninja"
+)
+source=("${msys2_repository_url}/releases/download/v${pkgver}/${_realname}-${pkgver}.tar.gz"
         "010-timespec.patch")
-sha512sums=('69f39fffdcd965c871e598118db38ddb74a3e75fd7a7965f8d236029fa891f6fcb6b671147c166ad08482bbd0737537fafe90aa8439a0ab62389f19150cc39d7'
-            '0e003df9d1d68a48bfa39e894df57dec09b87e1f25b6bd61ac02b7c6a55b975f873fa9abe649d25fe2bc042b0c027d42705fbc9480e5aa3340a04a1e23b95261')
+sha256sums=('21c692105db15299b5529af81a11a7ad80397f92c122bd7bf1e4a4b0e85654f7'
+            '29f9e5360f499f74971923ea8aece0eb98a47abd1ed09c0c4bbb7b1e2eb93e60')
 
 prepare() {
   cd "${srcdir}"/${_realname}-${pkgver}
@@ -25,8 +27,6 @@ prepare() {
 }
 
 build() {
-  mkdir -p build-${MSYSTEM} && cd build-${MSYSTEM}
-
   declare -a extra_config
   if check_option "debug" "n"; then
     extra_config+=("-DCMAKE_BUILD_TYPE=Release")
@@ -34,28 +34,35 @@ build() {
     extra_config+=("-DCMAKE_BUILD_TYPE=Debug")
   fi
 
+  if [[ ${MSYSTEM} == CLANG* ]]; then
+    # Otherwise realloc is a macro, and std::realloc fails to compile.
+    extra_config+=("-DMEMORY_LEAK_DETECTION=OFF")
+  fi
+
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
-  ${MINGW_PREFIX}/bin/cmake \
-    -G Ninja \
+  cmake \
+    -GNinja \
     -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
+    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
     "${extra_config[@]}" \
     -DC++11=ON \
     -DTESTS=ON \
     -DEXAMPLES=ON \
-    ../${_realname}-${pkgver}
+    -S ${_realname}-${pkgver} \
+    -B build-${MSYSTEM}
 
-  ${MINGW_PREFIX}/bin/cmake --build ./
+  cmake --build build-${MSYSTEM}
 }
 
 check() {
-  cd "${srcdir}"/build-${MSYSTEM}
-  ${MINGW_PREFIX}/bin/ctest ./ || true
+  ctest --test-dir build-${MSYSTEM} --output-on-failure || true
 }
 
 package() {
-  cd "${srcdir}"/build-${MSYSTEM}
-  DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/cmake --build ./ --target install
+  DESTDIR="${pkgdir}" cmake --install build-${MSYSTEM}
 
-  install -Dm644 "${srcdir}"/${_realname}-${pkgver}/README.md "${pkgdir}"${MINGW_PREFIX}/share/doc/${_realname}/README.md
-  install -Dm644 "${srcdir}"/${_realname}-${pkgver}/COPYING "${pkgdir}"${MINGW_PREFIX}/share/licenses/${_realname}/COPYING
+  install -Dm644 "${srcdir}"/${_realname}-${pkgver}/README.md \
+    "${pkgdir}"${MINGW_PREFIX}/share/doc/${_realname}/README.md
+  install -Dm644 "${srcdir}"/${_realname}-${pkgver}/COPYING \
+    "${pkgdir}"${MINGW_PREFIX}/share/licenses/${_realname}/COPYING
 }
