git: work around -j15 errors
Sometimes, a highly parallel build ends with

```
make: INTERNAL: Exiting with 12 jobserver tokens available; should be 15!
```

(with unnervingly different counts of available jobserver tokens). This
seems to be fixed sporadically, so let's just run the `make` in a loop
because the parallelization really speeds up things a lot on multi-core
machines.

See also https://github.com/Alexpux/MSYS2-packages/issues/232.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/mingw-w64-git/PKGBUILD b/mingw-w64-git/PKGBUILD
--- a/mingw-w64-git/PKGBUILD
+++ b/mingw-w64-git/PKGBUILD
@@ -65,11 +65,19 @@ build() {
   # use the PARALLEL_BUILD environment variable if is set,
   # otherwise default to one job at a time
   # for example, PARALLEL_BUILD=-j8
-  make "${PARALLEL_BUILD:--j1}" \
+  counter=0
+  while ! make "${PARALLEL_BUILD:--j1}" \
     ASCIIDOC=asciidoctor ASCIIDOC_HTML=html5 ASCIIDOC_DOCBOOK=docbook45 \
     ASCIIDOC_EXTRA="'-alitdd=&#45;&#45;'" \
     ASCIIDOC_CONF="-I$ASCIIDOCTORDIR -rman-inline-macro" \
-    all html man &&
+    all html man
+  do
+    counter=$(($counter+1))
+    test $counter -lt 5 || {
+      echo "Could not build (tried 5 times)" >&2
+      exit 1
+    }
+  done &&
 
   (cd $startdir &&
    for basename in git-bash git-cmd git-wrapper gitk
@@ -96,7 +104,6 @@ print-builtins:
 EOF
   make -f print.mak print-builtins | tr ' ' '\n' > builtins.txt &&
 
-  # git-credential-wincred.exe
   CC=gcc make -C contrib/credential/wincred
 }
 
