Rename python3 packages to python and update to latest. Round 1

diff --git a/mingw-w64-python-hypothesis/PKGBUILD b/mingw-w64-python-hypothesis/PKGBUILD
--- a/mingw-w64-python-hypothesis/PKGBUILD
+++ b/mingw-w64-python-hypothesis/PKGBUILD
@@ -2,36 +2,39 @@
 
 _realname=hypothesis
 pkgbase=mingw-w64-python-${_realname}
-pkgname=("${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
-pkgver=4.43.7
+pkgname=("${MINGW_PACKAGE_PREFIX}-python-${_realname}")
+provides=("${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
+conflicts=("${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
+replaces=("${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
+pkgver=4.56.3
 pkgrel=1
 pkgdesc="Advanced Quickcheck style testing library for Python (mingw-w64)"
 arch=('any')
 url='https://hypothesis.readthedocs.org'
 license=('MIT')
-depends=("${MINGW_PACKAGE_PREFIX}-python3"
-         "${MINGW_PACKAGE_PREFIX}-python3-attrs"
-         "${MINGW_PACKAGE_PREFIX}-python3-coverage")
-optdepends=("${MINGW_PACKAGE_PREFIX}-python3-pytz: for datetime and django module"
-            "${MINGW_PACKAGE_PREFIX}-python3-faker: for fakefactory and django module"
-            "${MINGW_PACKAGE_PREFIX}-python3-django: for django module"
-            "${MINGW_PACKAGE_PREFIX}-python3-numpy: for numpy module"
-            "${MINGW_PACKAGE_PREFIX}-python3-pytest: for pytest module")
-makedepends=("${MINGW_PACKAGE_PREFIX}-python3-setuptools")
-#checkdepends=("${MINGW_PACKAGE_PREFIX}-python3-pytest-runner"
-#              "${MINGW_PACKAGE_PREFIX}-python3-flake8"
-#              "${MINGW_PACKAGE_PREFIX}-python3-pytz"
-#              "${MINGW_PACKAGE_PREFIX}-python3-numpy"
-#              "${MINGW_PACKAGE_PREFIX}-python3-faker" 
-#              "${MINGW_PACKAGE_PREFIX}-python3-flaky"
-#              "${MINGW_PACKAGE_PREFIX}-python3-pytest-benchmark"
-#              "${MINGW_PACKAGE_PREFIX}-python3-django"
-#              "${MINGW_PACKAGE_PREFIX}-python3-pytest-xdist"
-#              "${MINGW_PACKAGE_PREFIX}-python3-mock"
-#              "${MINGW_PACKAGE_PREFIX}-python3-pandas")
+depends=("${MINGW_PACKAGE_PREFIX}-python"
+         "${MINGW_PACKAGE_PREFIX}-python-attrs"
+         "${MINGW_PACKAGE_PREFIX}-python-coverage")
+optdepends=("${MINGW_PACKAGE_PREFIX}-python-pytz: for datetime and django module"
+            "${MINGW_PACKAGE_PREFIX}-python-faker: for fakefactory and django module"
+            "${MINGW_PACKAGE_PREFIX}-python-django: for django module"
+            "${MINGW_PACKAGE_PREFIX}-python-numpy: for numpy module"
+            "${MINGW_PACKAGE_PREFIX}-python-pytest: for pytest module")
+makedepends=("${MINGW_PACKAGE_PREFIX}-python-setuptools")
+#checkdepends=("${MINGW_PACKAGE_PREFIX}-python-pytest-runner"
+#              "${MINGW_PACKAGE_PREFIX}-python-flake8"
+#              "${MINGW_PACKAGE_PREFIX}-python-pytz"
+#              "${MINGW_PACKAGE_PREFIX}-python-numpy"
+#              "${MINGW_PACKAGE_PREFIX}-python-faker" 
+#              "${MINGW_PACKAGE_PREFIX}-python-flaky"
+#              "${MINGW_PACKAGE_PREFIX}-python-pytest-benchmark"
+#              "${MINGW_PACKAGE_PREFIX}-python-django"
+#              "${MINGW_PACKAGE_PREFIX}-python-pytest-xdist"
+#              "${MINGW_PACKAGE_PREFIX}-python-mock"
+#              "${MINGW_PACKAGE_PREFIX}-python-pandas")
 options=('staticlibs' 'strip' '!debug')
 source=("${_realname}-${pkgver}.tar.gz"::"https://github.com/HypothesisWorks/hypothesis/archive/hypothesis-python-${pkgver}.tar.gz")
-sha512sums=('bf074f74b1bf0d79405cb529c4e639794117a28b5e21cd6c86125dee232bb1dfa831ffda15779f46c795c0a31e896d96f0f9f197c40de89e742caca57041f8c2')
+sha512sums=('efb01d25c31f5230c802909f1c8a6a709c5fcaecd5bbdba451445b2673f7051d402a5ce919c6ab26531662163604b34cea9d3233dc83a9e6cf20dc22c47ba765')
 
 # Helper macros to help make tasks easier #
 apply_patch_with_msg() {
@@ -57,11 +60,11 @@ prepare() {
   sed -i "/FutureWarning/a \    filterwarnings('ignore', category=DeprecationWarning, module='pandas.core')" \
        ${_realname}-${_realname}-python-$pkgver/hypothesis-python/tests/common/setup.py
 
-  rm -rf python3-build-${CARCH} | true
-  cp -r "${_realname}-${_realname}-python-${pkgver}" "python3-build-${CARCH}"
+  rm -rf python-build-${CARCH} | true
+  cp -r "${_realname}-${_realname}-python-${pkgver}" "python-build-${CARCH}"
 
   # Set version for setuptools_scm
-  export SETUPTOOLS_SCM_PRETEND_VERSION=$pkgver
+  export SETUPTOOLS_SCM_PRETEND_VERSION=${pkgver}
   export LC_CTYPE=en_US.UTF-8
 }
 
@@ -70,24 +73,24 @@ prepare() {
 # but sometimes, you want to do a check before install which would
 # also trigger the build.
 build() {
-  msg "Python 3 build for ${CARCH}"
-  cd "${srcdir}/python3-build-${CARCH}/hypothesis-python"
-  ${MINGW_PREFIX}/bin/python3 setup.py build
+  msg "Python build for ${CARCH}"
+  cd "${srcdir}/python-build-${CARCH}/hypothesis-python"
+  ${MINGW_PREFIX}/bin/python setup.py build
 }
 
 # Comment out until we can get this to work.
 #check() {
-#  msg "Python 3 test for ${CARCH}"
-#  cd "${srcdir}/python3-build-${CARCH}/hypothesis-python"
+#  msg "Python test for ${CARCH}"
+#  cd "${srcdir}/python-build-${CARCH}/hypothesis-python"
 #  mv tests/django ../
-#  ${MINGW_PREFIX}/bin/python3 setup.py pytest --addopts -n16
+#  ${MINGW_PREFIX}/bin/python setup.py pytest --addopts -n16
 #  mv ../django tests/
-#  PYTHONPATH="$PWD/build/lib:$PYTHONPATH" ${MINGW_PREFIX}/bin/python3 -m tests.django.manage test tests.django || warning "Tests failed"
+#  PYTHONPATH="$PWD/build/lib:$PYTHONPATH" ${MINGW_PREFIX}/bin/python -m tests.django.manage test tests.django || warning "Tests failed"
 #}
 
 package() {
-  cd "${srcdir}/python3-build-${CARCH}/hypothesis-python"
+  cd "${srcdir}/python-build-${CARCH}/hypothesis-python"
   MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=" \
-  ${MINGW_PREFIX}/bin/python3 setup.py install --prefix=${MINGW_PREFIX} \
+  ${MINGW_PREFIX}/bin/python setup.py install --prefix=${MINGW_PREFIX} \
     --root="${pkgdir}" --optimize=1 --skip-build
 }
