use introspection to obtain petsc-build version

diff --git a/mingw-w64-sundials/PKGBUILD b/mingw-w64-sundials/PKGBUILD
--- a/mingw-w64-sundials/PKGBUILD
+++ b/mingw-w64-sundials/PKGBUILD
@@ -43,8 +43,6 @@ sha256sums=('48da7baa8152ddb22aed1b02d82d1dbb4fbfea22acf67634011aa0303a100a43'
             'af3391ca031778c238e430d3a78631842f5407806020e90529de14850addce69'
             '0d57be6ac23224a768159e958676a3b5e541d57cf9df9763a4a101932382d3f5')
 
-_petsc_version=3.14.5
-
 prepare() {
   patch -d ${_realname}-${pkgver} -p1 < 0001-sundials-link-errors.patch
   patch -d ${_realname}-${pkgver} -p1 < 0002-sundials-missing-export.patch
@@ -58,6 +56,16 @@ build() {
   [[ -d build-${MINGW_PACKAGE_PREFIX} ]] && rm -rf build-${MINGW_PACKAGE_PREFIX}
 
   local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
+
+  _petsc_version=$(pacman -Qi ${MINGW_PACKAGE_PREFIX}-petsc-build \
+                   | grep --color=never "Version" \
+                   | sed 's/^.*: *\([^-]\+\).*$/\1/')
+
+  if [[ ! -d "${MINGW_PREFIX}/src/petsc-${_petsc_version}" ]]; then
+    echo "Missing the PETSc build directory for version: ${_petsc_version}." >&2
+    echo "It should be located at ${PREFIX_WIN}/src/petsc-${_petsc_version}." >&2
+    exit 1
+  fi
 
   I_MPI_ROOT="" \
   MSYS2_ARG_CONV_EXCL="CMAKE_INSTALL_PREFIX=;EXAMPLES_INSTALL_PATH=" \
@@ -182,13 +190,13 @@ package() {
       -i "${pkgdir}${MINGW_PREFIX}"/lib/cmake/sundials/SUNDIALSConfig.cmake
 
   # Repoint the PETSc configuration to the runtime package (rather than the -build package).
-  sed -e "s|src/petsc-${_petsc_version}/dmo/include|include/petsc/dmo|g" \
+  sed -e "s|src/petsc-[^/]\+/dmo/include|include/petsc/dmo|g" \
       -i "${pkgdir}${MINGW_PREFIX}"/lib/cmake/sundials/SUNDIALSConfig.cmake
       
-  sed -e "s|src/petsc-${_petsc_version}/dmo/lib|lib/petsc/dmo|g" \
+  sed -e "s|src/petsc-[^/]\+/dmo/lib|lib/petsc/dmo|g" \
       -i "${pkgdir}${MINGW_PREFIX}"/lib/cmake/sundials/SUNDIALSConfig.cmake
 
-  sed -e "s|src/petsc-${_petsc_version}/include|include/petsc|g" \
+  sed -e "s|src/petsc-[^/]\+/include|include/petsc|g" \
       -i "${pkgdir}${MINGW_PREFIX}"/lib/cmake/sundials/SUNDIALSConfig.cmake
 
   # Fix a condition which will incorrectly fail.
@@ -202,8 +210,8 @@ package() {
     _relative_root=$(realpath --relative-to="${_fdir}" "${pkgdir}${MINGW_PREFIX}")
     sed -e "s|${PREFIX_WIN}|\$\{CMAKE_CURRENT_LIST_DIR\}/${_relative_root}|g"   -i "${_f}"
     sed -e "s|${MINGW_PREFIX}|\$\{CMAKE_CURRENT_LIST_DIR\}/${_relative_root}|g" -i "${_f}"
-    sed -e "s|src/petsc-${_petsc_version}/dmo/include|include/petsc/dmo|g"      -i "${_f}"
-    sed -e "s|src/petsc-${_petsc_version}/dmo/lib|lib/petsc/dmo|g"              -i "${_f}"
-    sed -e "s|src/petsc-${_petsc_version}/include|include/petsc|g"              -i "${_f}"
+    sed -e "s|src/petsc-[^/]\+/dmo/include|include/petsc/dmo|g"      -i "${_f}"
+    sed -e "s|src/petsc-[^/]\+/dmo/lib|lib/petsc/dmo|g"              -i "${_f}"
+    sed -e "s|src/petsc-[^/]\+/include|include/petsc|g"              -i "${_f}"
   done
 }
