nodejs: fix npm script

diff --git a/mingw-w64-nodejs/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.patch b/mingw-w64-nodejs/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.patch
--- a/mingw-w64-nodejs/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.patch
+++ b/mingw-w64-nodejs/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.patch
@@ -29,46 +29,28 @@ diff --git a/deps/npm/bin/npm b/deps/npm/bin/npm
 index 5acd6fb6..dc01687e 100755
 --- a/deps/npm/bin/npm
 +++ b/deps/npm/bin/npm
-@@ -19,6 +19,9 @@
+@@ -18,7 +18,7 @@
+ # this path is passed to node.exe, so it needs to match whatever
  # kind of paths Node.js thinks it's using, typically win32 paths.
  CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"
- NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
-+if [ `uname` = 'MINGW*' ] ; then
-+  NPM_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npm-cli.js"
-+fi
+-NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
++NPM_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npm-cli.js"
  
  NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
  if [ $? -ne 0 ]; then
-@@ -27,6 +30,9 @@
+@@ -26,7 +26,7 @@
+   echo "Could not determine Node.js install directory" >&2
    exit 1
  fi
- NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
-+if [ `uname` = 'MINGW*' ] ; then
-+  NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/../lib/node_modules/npm/bin/npm-cli.js"
-+fi
+-NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
++NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/../lib/node_modules/npm/bin/npm-cli.js"
  
  # a path that will fail -f test on any posix bash
  NPM_WSL_PATH="/.."
-diff --git a/deps/npm/bin/npx b/deps/npm/bin/npx
---- a/deps/npm/bin/npx
-+++ b/deps/npm/bin/npx
-@@ -31,6 +31,11 @@
- NPX_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js"
- NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
- NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js"
-+if [ `uname` = 'MINGW*' ] ; then
-+  NPM_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npm-cli.js"
-+  NPX_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npx-cli.js"
-+  NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/../lib/node_modules/npm/bin/npx-cli.js"
-+fi
- 
- # a path that will fail -f test on any posix bash
- NPX_WSL_PATH="/.."
 diff --git a/deps/npm/bin/npm.cmd b/deps/npm/bin/npm.cmd
 index 880554dc..12507ba1 100644
 --- a/deps/npm/bin/npm.cmd
-+++ b/deps/npm/bin/npm.cmd
-@@ -8,9 +8,9 @@ IF NOT EXIST "%NODE_EXE%" (
+@@ -8,9 +8,9 @@
    SET "NODE_EXE=node"
  )
  
@@ -80,6 +62,23 @@ index 880554dc..12507ba1 100644
  )
  IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
    SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
+diff --git a/deps/npm/bin/npx b/deps/npm/bin/npx
+--- a/deps/npm/bin/npx
++++ b/deps/npm/bin/npx
+@@ -27,10 +27,10 @@
+   echo "Could not determine Node.js install directory" >&2
+   exit 1
+ fi
+-NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
+-NPX_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js"
++NPM_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npm-cli.js"
++NPX_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npx-cli.js"
+ NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
+-NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js"
++NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/../lib/node_modules/npm/bin/npx-cli.js"
+ 
+ # a path that will fail -f test on any posix bash
+ NPX_WSL_PATH="/.."
 diff --git a/deps/npm/lib/npm.js b/deps/npm/lib/npm.js
 index e5871260..ad9ed251 100644
 --- a/deps/npm/lib/npm.js
