KDEF5: Fix for static/shared build

diff --git a/mingw-w64-PKGBUILD-common/build-kf5 b/mingw-w64-PKGBUILD-common/build-kf5
--- a/mingw-w64-PKGBUILD-common/build-kf5
+++ b/mingw-w64-PKGBUILD-common/build-kf5
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+if [[ "$1" == "shared" ]]; then
+  echo "Building shared"
+elif [[ "$1" == "static" ]]; then
+  echo "Building static"
+else
+  echo "${0} :: Error :: Please pass static or shared"
+  exit 1
+fi
+
 THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 # Listed in tier-order
@@ -28,7 +37,7 @@ solid-qt5
 
 for pkg in "${pkgs[@]}"; do
   pushd ${THISDIR}/../mingw-w64-${pkg}
-  export KF5_VARIANT=shared
+  export KF5_VARIANT=$1
   rm -rf *pkg*xz src pkg
   makepkg-mingw -siLf --noconfirm || exit 1
   popd
