benchmark: fix mingw build

diff --git a/mingw-w64-benchmark/PKGBUILD b/mingw-w64-benchmark/PKGBUILD
--- a/mingw-w64-benchmark/PKGBUILD
+++ b/mingw-w64-benchmark/PKGBUILD
@@ -14,18 +14,21 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
              "${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-gtest")
 options=('staticlibs' 'strip')
-source=("${_realname}-${pkgver}.tar.gz::https://github.com/google/benchmark/archive/v${pkgver}.tar.gz")
-sha256sums=('f8e525db3c42efc9c7f3bc5176a8fa893a9a9920bbd08cef30fb56a51854d60d')
+source=("${_realname}-${pkgver}.tar.gz::https://github.com/google/benchmark/archive/v${pkgver}.tar.gz"
+        "benchmark-mingw.patch")
+sha256sums=('f8e525db3c42efc9c7f3bc5176a8fa893a9a9920bbd08cef30fb56a51854d60d'
+            '00a34d29f1dc4339513c4ebabd00560b446624a3380edc98a57c0c43484473f7')
 
 prepare() {
   cd "${srcdir}/${_realname}-${pkgver}"
+  patch -Np1 -i "${srcdir}/benchmark-mingw.patch"
   sed -i "s|v0.0.0|v${pkgver}|g" "cmake/GetGitVersion.cmake"
 }
 
 build() {
-  [[ -d "${srcdir}/build-${MINGW_CHOST}" ]] && rm -rf "${srcdir}/build-${MINGW_CHOST}"
-  mkdir -p "${srcdir}"/build-${MINGW_CHOST} && cd "${srcdir}"/build-${MINGW_CHOST}
-
+  # Shared Build
+  [[ -d "${srcdir}/build-${MINGW_CHOST}-shared" ]] && rm -rf "${srcdir}/build-${MINGW_CHOST}-shared"
+  mkdir -p "${srcdir}"/build-${MINGW_CHOST}-shared && cd "${srcdir}"/build-${MINGW_CHOST}-shared
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
   ${MINGW_PREFIX}/bin/cmake \
       -G"MSYS Makefiles" \
@@ -33,23 +36,42 @@ build() {
       -DCMAKE_BUILD_TYPE="Release" \
       -DBUILD_SHARED_LIBS="ON" \
       ../${_realname}-${pkgver}
-
+      
+  make
+  
+  # Static Build
+  [[ -d "${srcdir}/build-${MINGW_CHOST}-static" ]] && rm -rf "${srcdir}/build-${MINGW_CHOST}-static"
+  mkdir -p "${srcdir}"/build-${MINGW_CHOST}-static && cd "${srcdir}"/build-${MINGW_CHOST}-static
+  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
+  ${MINGW_PREFIX}/bin/cmake \
+      -G"MSYS Makefiles" \
+      -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" \
+      -DCMAKE_BUILD_TYPE="Release" \
+      -DBUILD_SHARED_LIBS="OFF" \
+      ../${_realname}-${pkgver}
+      
   make
 }
 
 check() {
-  cd "${srcdir}/build-${MINGW_CHOST}"
+  # Shared Check
+  cd "${srcdir}/build-${MINGW_CHOST}-shared"
+  make test || echo "Ignore for now, as the test is expected to fail: https://github.com/google/benchmark/issues/578"
+  
+  # Static Check
+  cd "${srcdir}/build-${MINGW_CHOST}-static"
   make test || echo "Ignore for now, as the test is expected to fail: https://github.com/google/benchmark/issues/578"
 }
 
 package() {
-  cd "${srcdir}/build-${MINGW_CHOST}"
+  # Shared Install
+  cd "${srcdir}/build-${MINGW_CHOST}-shared"
   make DESTDIR="${pkgdir}" install
-  install -Dm644 "${srcdir}/${_realname}-${pkgver}/LICENSE" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
   
-  local PREFIX_ROOT=$(cygpath -wm /usr)
-  # fix cmake config files
-  for _f in "${pkgdir}${MINGW_PREFIX}"/lib/cmake/${_realname}/*.cmake; do
-    sed -e "s|${PREFIX_ROOT}|/usr|g" -i ${_f}
-  done
+  # Static Install
+  cd "${srcdir}/build-${MINGW_CHOST}-static"
+  make DESTDIR="${pkgdir}" install
+  
+  # License
+  install -Dm644 "${srcdir}/${_realname}-${pkgver}/LICENSE" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
 }
