Fix formatting. Replace TAB with two spaces

diff --git a/mingw-w64-OpenBLAS-git/PKGBUILD b/mingw-w64-OpenBLAS-git/PKGBUILD
--- a/mingw-w64-OpenBLAS-git/PKGBUILD
+++ b/mingw-w64-OpenBLAS-git/PKGBUILD
@@ -15,67 +15,67 @@ groups=("${_mingw_suff}")
 options=('strip' 'staticlibs')
 depends=("${_mingw_suff}-gcc-libs")
 makedepends=("git" 
-		"${_mingw_suff}-gcc"
-		"${_mingw_suff}-gcc-fortran")
+    "${_mingw_suff}-gcc"
+    "${_mingw_suff}-gcc-fortran")
 source=("$_realname"::"git://github.com/xianyi/OpenBLAS")
 sha1sums=('SKIP')
 
 pkgver() {
-	cd "$srcdir/$_realname"
-	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+  cd "$srcdir/$_realname"
+  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
 build() {
-	mkdir -p ${srcdir}/build-${CARCH} && cd ${srcdir}/build-${CARCH}
-	git clone ${srcdir}/${_realname} .
-	make -f Makefile CC=gcc FC=gfortran LIBNAME=libopenblasp.a DYNAMIC_ARCH=1 2>make.err
+  mkdir -p ${srcdir}/build-${CARCH} && cd ${srcdir}/build-${CARCH}
+  git clone ${srcdir}/${_realname} .
+  make -f Makefile CC=gcc FC=gfortran LIBNAME=libopenblasp.a DYNAMIC_ARCH=1 2>make.err
 }
 
 package() {
-	cd ${srcdir}/build-${CARCH}
-	if [ -f libopenblas.dll ]; then
-		if [ -f exports/libopenblas.def ]; then
-			dlltool -d exports/libopenblas.def -l libopenblas.dll.a
-		else
-			echo "Cannot build export library" >&2
-			exit 1
-		fi
-	else
-		echo "DLL not found" >&2
-		exit 1
-	fi
-	mkdir -p "${pkgdir}${MINGW_PREFIX}/bin"
-	mkdir -p "${pkgdir}${MINGW_PREFIX}/lib"
+  cd ${srcdir}/build-${CARCH}
+  if [ -f libopenblas.dll ]; then
+    if [ -f exports/libopenblas.def ]; then
+      dlltool -d exports/libopenblas.def -l libopenblas.dll.a
+    else
+      echo "Cannot build export library" >&2
+      exit 1
+    fi
+  else
+    echo "DLL not found" >&2
+    exit 1
+  fi
+  mkdir -p "${pkgdir}${MINGW_PREFIX}/bin"
+  mkdir -p "${pkgdir}${MINGW_PREFIX}/lib"
 
-	make $MAKEFLAGS -f Makefile LIBNAME=libopenblasp.a DESTDIR="${pkgdir}" PREFIX="${MINGW_PREFIX}" install
+  make $MAKEFLAGS -f Makefile LIBNAME=libopenblasp.a DESTDIR="${pkgdir}" PREFIX="${MINGW_PREFIX}" install
 
-	if [ -f libopenblas.dll ]; then
-		cp -f libopenblas.dll "${pkgdir}$MINGW_PREFIX/bin/"
-	else
-		echo "DLL not found" >&2
-		exit 1
-	fi
+  if [ -f libopenblas.dll ]; then
+    cp -f libopenblas.dll "${pkgdir}$MINGW_PREFIX/bin/"
+  else
+    echo "DLL not found" >&2
+    exit 1
+  fi
 
-	if [ -f libopenblas.dll.a ]; then
-		cp -f libopenblas.dll.a "${pkgdir}$MINGW_PREFIX/lib/"
-	else
-		echo "Export library not found" >&2
-		exit 1
-	fi
+  if [ -f libopenblas.dll.a ]; then
+    cp -f libopenblas.dll.a "${pkgdir}$MINGW_PREFIX/lib/"
+  else
+    echo "Export library not found" >&2
+    exit 1
+  fi
 
-	if [ -f libopenblasp.a ]; then
-		rm -f "${pkgdir}$MINGW_PREFIX/lib/libopenblasp.a"
-		rm -f "${pkgdir}$MINGW_PREFIX/lib/libopenblas.a"
-		cp -f libopenblasp.a "${pkgdir}$MINGW_PREFIX/lib/libopenblas.a"
-	else
-		echo "Static library not found" >&2
-		exit 1
-	fi
+  if [ -f libopenblasp.a ]; then
+    rm -f "${pkgdir}$MINGW_PREFIX/lib/libopenblasp.a"
+    rm -f "${pkgdir}$MINGW_PREFIX/lib/libopenblas.a"
+    cp -f libopenblasp.a "${pkgdir}$MINGW_PREFIX/lib/libopenblas.a"
+  else
+    echo "Static library not found" >&2
+    exit 1
+  fi
 
-	# Copy Licencse
-	mkdir -p ${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname  
-	cp -f ${srcdir}/${_realname}/LICENSE \
-		${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname
-	cp -f ${srcdir}/${_realname}/lapack-netlib/LICENSE \
-		${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname/LICENSE-lapack
+  # Copy Licencse
+  mkdir -p ${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname  
+  cp -f ${srcdir}/${_realname}/LICENSE \
+    ${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname
+  cp -f ${srcdir}/${_realname}/lapack-netlib/LICENSE \
+    ${pkgdir}${MINGW_PREFIX}/share/licenses/$_realname/LICENSE-lapack
 }
diff --git a/mingw-w64-ogre3d-hg/PKGBUILD b/mingw-w64-ogre3d-hg/PKGBUILD
--- a/mingw-w64-ogre3d-hg/PKGBUILD
+++ b/mingw-w64-ogre3d-hg/PKGBUILD
@@ -15,25 +15,25 @@ url="http://www.ogre3d.org/"
 license=("LGPL")
 makedepends=("${_mingw_suff}-gcc" "${_mingw_suff}-pkg-config" "${_mingw_suff}-cmake" "mercurial")
 depends=("${_mingw_suff}-boost"
-		"${_mingw_suff}-cppunit"
-		"${_mingw_suff}-FreeImage"
-		"${_mingw_suff}-freetype"
-		"${_mingw_suff}-glsl-optimizer"
-		"${_mingw_suff}-hlsl2glsl"
-		"${_mingw_suff}-nvidia-cg-toolkit"
-		"${_mingw_suff}-ois"
-		"${_mingw_suff}-tinyxml"
-		"${_mingw_suff}-zlib"
-		"${_mingw_suff}-zziplib"
-		#"${_mingw_suff}-intel-tbb"
-		)
+    "${_mingw_suff}-cppunit"
+    "${_mingw_suff}-FreeImage"
+    "${_mingw_suff}-freetype"
+    "${_mingw_suff}-glsl-optimizer"
+    "${_mingw_suff}-hlsl2glsl"
+    "${_mingw_suff}-nvidia-cg-toolkit"
+    "${_mingw_suff}-ois"
+    "${_mingw_suff}-tinyxml"
+    "${_mingw_suff}-zlib"
+    "${_mingw_suff}-zziplib"
+    #"${_mingw_suff}-intel-tbb"
+    )
 options=('staticlibs' '!strip') # '!buildflags'
 source=("${_realname}-${pkgver}.tar.xz"{,.sig}
-		ogre-1.9.0-fix-cflags.patch
-		ogre-endlessworld-fix.patch
-		ogre-freeimage-fix.patch
-		use-mingw-w64-directx.patch
-		mingw-w64-fix.patch)
+    ogre-1.9.0-fix-cflags.patch
+    ogre-endlessworld-fix.patch
+    ogre-freeimage-fix.patch
+    use-mingw-w64-directx.patch
+    mingw-w64-fix.patch)
 md5sums=('f0e6046fbe17b874a5708b4823cce603'
          'SKIP'
          'a2cbfc846906bbb80c7b05d2d60a2779'
@@ -46,103 +46,103 @@ _buildtype=Release
 
 # source PKGBUILD && mksource
 mksource() {
-	[[ -x /usr/bin/hg ]] || (echo "hg not found. Install mercurial." && return 1)
+  [[ -x /usr/bin/hg ]] || (echo "hg not found. Install mercurial." && return 1)
 
-	__hgroot='https://bitbucket.org/sinbad'
-	__hgrepo='ogre'
-	__hgbranch='default'
-	__hgrev="v1-9"
+  __hgroot='https://bitbucket.org/sinbad'
+  __hgrepo='ogre'
+  __hgbranch='default'
+  __hgrev="v1-9"
 
-	hg clone -u ${__hgrev} "${__hgroot}/${__hgrepo}/" ${__hgrepo}
-	#hg clone -b ${__hgbranch} "${__hgroot}${__hgrepo}#${__hgrev}" ${__hgrepo}
+  hg clone -u ${__hgrev} "${__hgroot}/${__hgrepo}/" ${__hgrepo}
+  #hg clone -b ${__hgbranch} "${__hgroot}${__hgrepo}#${__hgrev}" ${__hgrepo}
 
-	pushd ${__hgrepo}
-		if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
-			printf 'You are not building the latest revision!\n'
-			printf "Consider updating __hgrev to $(hg id -r ${__hgbranch}).\n"
-		fi
-		__revis="r$(hg identify -n).$(hg identify -i)"
-	popd
+  pushd ${__hgrepo}
+    if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
+      printf 'You are not building the latest revision!\n'
+      printf "Consider updating __hgrev to $(hg id -r ${__hgbranch}).\n"
+    fi
+    __revis="r$(hg identify -n).$(hg identify -i)"
+  popd
 
-	mv ${__hgrepo} ${_realname}-${_base_ver}.${__revis}
-	find ${_realname}-${_base_ver}.${__revis} -depth -type d -name .hg -exec rm -rf {} \;
-	rm ${_realname}-${_base_ver}.${__revis}/{.hgignore,.hgtags}
-	tar -cJf ${_realname}-${_base_ver}.${__revis}.tar.xz ${_realname}-${_base_ver}.${__revis}/*
-	rm -r ${_realname}-${_base_ver}.${__revis}
+  mv ${__hgrepo} ${_realname}-${_base_ver}.${__revis}
+  find ${_realname}-${_base_ver}.${__revis} -depth -type d -name .hg -exec rm -rf {} \;
+  rm ${_realname}-${_base_ver}.${__revis}/{.hgignore,.hgtags}
+  tar -cJf ${_realname}-${_base_ver}.${__revis}.tar.xz ${_realname}-${_base_ver}.${__revis}/*
+  rm -r ${_realname}-${_base_ver}.${__revis}
 
-	gpg --detach-sign ${_realname}-${_base_ver}.${__revis}.tar.xz
+  gpg --detach-sign ${_realname}-${_base_ver}.${__revis}.tar.xz
 
-	#scp ${pkgname}-${_base_ver}.tar.xz nym:/srv/ftp/other/vim/
-	#scp ${pkgname}-${_base_ver}.tar.xz.sig nym:/srv/ftp/other/vim/
+  #scp ${pkgname}-${_base_ver}.tar.xz nym:/srv/ftp/other/vim/
+  #scp ${pkgname}-${_base_ver}.tar.xz.sig nym:/srv/ftp/other/vim/
 }
 
 prepare() {
-	cd "${srcdir}/${_realname}-${pkgver}"
-	patch -p1 -i ${srcdir}/ogre-1.9.0-fix-cflags.patch
-	patch -p0 -i ${srcdir}/ogre-endlessworld-fix.patch
-	patch -p1 -i ${srcdir}/ogre-freeimage-fix.patch
-	patch -p1 -i ${srcdir}/use-mingw-w64-directx.patch
-	patch -p1 -i ${srcdir}/mingw-w64-fix.patch
+  cd "${srcdir}/${_realname}-${pkgver}"
+  patch -p1 -i ${srcdir}/ogre-1.9.0-fix-cflags.patch
+  patch -p0 -i ${srcdir}/ogre-endlessworld-fix.patch
+  patch -p1 -i ${srcdir}/ogre-freeimage-fix.patch
+  patch -p1 -i ${srcdir}/use-mingw-w64-directx.patch
+  patch -p1 -i ${srcdir}/mingw-w64-fix.patch
 }
 
 build() {
-	mkdir -p ${pkgdir}${MINGW_PREFIX}
-	pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
-	export PREFIX_WIN=`pwd -W`
-	popd > /dev/null
+  mkdir -p ${pkgdir}${MINGW_PREFIX}
+  pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
+  export PREFIX_WIN=`pwd -W`
+  popd > /dev/null
 
-	pushd ${MINGW_PREFIX} > /dev/null
-	export PREFIX_DEPS=`pwd -W`
-	popd > /dev/null
+  pushd ${MINGW_PREFIX} > /dev/null
+  export PREFIX_DEPS=`pwd -W`
+  popd > /dev/null
 
-	case ${MINGW_CHOST} in
-		i686*)
-			local _march=pentium4 #i686
-			local _tune=generic #generic
-		;;
-		x86_64*)
-			local _march=core2
-			local _tune=nocona
-		;;
-	esac
-	export CFLAGS="-O3 -pipe -march=${_march} -mtune=${_tune}"
-	export CXXFLAGS="-O3 -pipe -march=${_march} -mtune=${_tune}"
-	export DXSDK_DIR=${PREFIX_DEPS}/${MINGW_CHOST}
-	mkdir ${srcdir}/build-${MINGW_CHOST} && cd ${srcdir}/build-${MINGW_CHOST}
-	${MINGW_PREFIX}/bin/cmake.exe \
-		-G"MSYS Makefiles" \
-		-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX_WIN} \
-		-DOGRE_DEPENDENCIES_DIR:PATH=${PREFIX_DEPS} \
-		-DOGRE_INSTALL_TOOLS=ON \
-		-DOGRE_COPY_DEPENDENCIES=OFF \
-		-DOGRE_INSTALL_DEPENDENCIES=OFF \
-		-DOGRE_BUILD_RENDERSYSTEM_D3D9=ON \
-		-DOGRE_BUILD_RENDERSYSTEM_D3D11=OFF \
-		-DCMAKE_BUILD_TYPE:STRING=${_buildtype} \
-		-DFREETYPE_FT2BUILD_INCLUDE_DIR=${PREFIX_DEPS}/include/freetype2 \
-		-DDirectX9_DXERR_LIBRARY=${PREFIX_DEPS}/${MINGW_CHOST}/lib/libdxerr9.a \
-		../${_realname}-${pkgver}
+  case ${MINGW_CHOST} in
+    i686*)
+      local _march=pentium4 #i686
+      local _tune=generic #generic
+    ;;
+    x86_64*)
+      local _march=core2
+      local _tune=nocona
+    ;;
+  esac
+  export CFLAGS="-O3 -pipe -march=${_march} -mtune=${_tune}"
+  export CXXFLAGS="-O3 -pipe -march=${_march} -mtune=${_tune}"
+  export DXSDK_DIR=${PREFIX_DEPS}/${MINGW_CHOST}
+  mkdir ${srcdir}/build-${MINGW_CHOST} && cd ${srcdir}/build-${MINGW_CHOST}
+  ${MINGW_PREFIX}/bin/cmake.exe \
+    -G"MSYS Makefiles" \
+    -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX_WIN} \
+    -DOGRE_DEPENDENCIES_DIR:PATH=${PREFIX_DEPS} \
+    -DOGRE_INSTALL_TOOLS=ON \
+    -DOGRE_COPY_DEPENDENCIES=OFF \
+    -DOGRE_INSTALL_DEPENDENCIES=OFF \
+    -DOGRE_BUILD_RENDERSYSTEM_D3D9=ON \
+    -DOGRE_BUILD_RENDERSYSTEM_D3D11=OFF \
+    -DCMAKE_BUILD_TYPE:STRING=${_buildtype} \
+    -DFREETYPE_FT2BUILD_INCLUDE_DIR=${PREFIX_DEPS}/include/freetype2 \
+    -DDirectX9_DXERR_LIBRARY=${PREFIX_DEPS}/${MINGW_CHOST}/lib/libdxerr9.a \
+    ../${_realname}-${pkgver}
 
-	make
+  make
 }
 
 package() {
-	cd "${srcdir}/build-${MINGW_CHOST}"
-	make -j1 install #DESTDIR="$pkgdir"
-	pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
+  cd "${srcdir}/build-${MINGW_CHOST}"
+  make -j1 install #DESTDIR="$pkgdir"
+  pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
 
-	mv bin/${_buildtype}/* bin/
-	rm -r bin/${_buildtype}
-	mv lib/${_buildtype}/* lib/
-	rm -r lib/${_buildtype}
+  mv bin/${_buildtype}/* bin/
+  rm -r bin/${_buildtype}
+  mv lib/${_buildtype}/* lib/
+  rm -r lib/${_buildtype}
 
-	sed -i "s|../../|../|g" \
-		bin/plugins.cfg \
-		bin/resources.cfg \
-		bin/quakemap.cfg
+  sed -i "s|../../|../|g" \
+    bin/plugins.cfg \
+    bin/resources.cfg \
+    bin/quakemap.cfg
 
-	mkdir -p share/cmake-2.8/Modules
-	mv CMake/* share/cmake-2.8/Modules/
-	rm -r CMake
-	popd > /dev/null
+  mkdir -p share/cmake-2.8/Modules
+  mv CMake/* share/cmake-2.8/Modules/
+  rm -r CMake
+  popd > /dev/null
 }
