Rebuild more packages to fix dependency from mingw-w64-crt.

diff --git a/mingw-w64-ogre3d-hg/PKGBUILD b/mingw-w64-ogre3d-hg/PKGBUILD
--- a/mingw-w64-ogre3d-hg/PKGBUILD
+++ b/mingw-w64-ogre3d-hg/PKGBUILD
@@ -3,8 +3,9 @@
 _realname=ogre3d
 _mingw_suff=mingw-w64-${CARCH}
 pkgname="${_mingw_suff}-${_realname}-hg"
-_rev=r6231.b30696af7aec
-pkgver=1.9.0.${_rev}
+_rev=r6387.f5a1b5c87545
+_base_ver=1.9.0
+pkgver=${_base_ver}.${_rev}
 pkgrel=1
 pkgdesc="A cross-platform 3D game engine (mingw-w64)"
 provides=("${_mingw_suff}-${_realname}")
@@ -35,7 +36,7 @@ source=("${_realname}-${pkgver}.tar.xz"{,.sig}
 		use-mingw-w64-directx.patch
 		mingw-w64-fix.patch
 )
-md5sums=('f18927975fb74472f2e48b80d363a301'
+md5sums=('f0e6046fbe17b874a5708b4823cce603'
          'SKIP'
          'a2cbfc846906bbb80c7b05d2d60a2779'
          '3c00c5584a8edcb4dc07a57697a73d59'
@@ -47,43 +48,43 @@ _buildtype=Release
 
 # source PKGBUILD && mksource
 mksource() {
-  [[ -x /usr/bin/hg ]] || (echo "hg not found. Install mercurial." && return 1)
+	[[ -x /usr/bin/hg ]] || (echo "hg not found. Install mercurial." && return 1)
 
-  __hgroot='https://bitbucket.org/sinbad'
-  __hgrepo='ogre'
-  __hgbranch='default'
-  __hgrev="v1-9"
+	__hgroot='https://bitbucket.org/sinbad'
+	__hgrepo='ogre'
+	__hgbranch='default'
+	__hgrev="v1-9"
 
-  hg clone -u ${__hgrev} "${__hgroot}/${__hgrepo}/" ${__hgrepo}
-  #hg clone -b ${__hgbranch} "${__hgroot}${__hgrepo}#${__hgrev}" ${__hgrepo}
+	hg clone -u ${__hgrev} "${__hgroot}/${__hgrepo}/" ${__hgrepo}
+	#hg clone -b ${__hgbranch} "${__hgroot}${__hgrepo}#${__hgrev}" ${__hgrepo}
 
-  pushd ${__hgrepo}
-  if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
-    printf 'You are not building the latest revision!\n'
-    printf "Consider updating __hgrev to $(hg id -r ${__hgbranch}).\n"
-  fi
-  __revis="r$(hg identify -n).$(hg identify -i)"
-  popd
+	pushd ${__hgrepo}
+		if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
+			printf 'You are not building the latest revision!\n'
+			printf "Consider updating __hgrev to $(hg id -r ${__hgbranch}).\n"
+		fi
+		__revis="r$(hg identify -n).$(hg identify -i)"
+	popd
 
-  mv ${__hgrepo} ${_realname}-${pkgver}.${__revis}
-  find ${_realname}-${pkgver}.${__revis} -depth -type d -name .hg -exec rm -rf {} \;
-  rm ${_realname}-${pkgver}.${__revis}/{.hgignore,.hgtags}
-  tar -cJf ${_realname}-${pkgver}.${__revis}.tar.xz ${_realname}-${pkgver}.${__revis}/*
-  rm -r ${_realname}-${pkgver}.${__revis}
+	mv ${__hgrepo} ${_realname}-${_base_ver}.${__revis}
+	find ${_realname}-${_base_ver}.${__revis} -depth -type d -name .hg -exec rm -rf {} \;
+	rm ${_realname}-${_base_ver}.${__revis}/{.hgignore,.hgtags}
+	tar -cJf ${_realname}-${_base_ver}.${__revis}.tar.xz ${_realname}-${_base_ver}.${__revis}/*
+	rm -r ${_realname}-${_base_ver}.${__revis}
 
-  gpg --detach-sign ${_realname}-${pkgver}.${__revis}.tar.xz
+	gpg --detach-sign ${_realname}-${_base_ver}.${__revis}.tar.xz
 
-  #scp ${pkgname}-${pkgver}.tar.xz nym:/srv/ftp/other/vim/
-  #scp ${pkgname}-${pkgver}.tar.xz.sig nym:/srv/ftp/other/vim/
+	#scp ${pkgname}-${_base_ver}.tar.xz nym:/srv/ftp/other/vim/
+	#scp ${pkgname}-${_base_ver}.tar.xz.sig nym:/srv/ftp/other/vim/
 }
 
 prepare() {
-  cd "${srcdir}/${_realname}-${pkgver}"
-  patch -p1 -i ${srcdir}/ogre-1.9.0-fix-cflags.patch
-  patch -p0 -i ${srcdir}/ogre-endlessworld-fix.patch
-  patch -p1 -i ${srcdir}/ogre-freeimage-fix.patch
-  patch -p1 -i ${srcdir}/use-mingw-w64-directx.patch
-  patch -p1 -i ${srcdir}/mingw-w64-fix.patch
+	cd "${srcdir}/${_realname}-${pkgver}"
+	patch -p1 -i ${srcdir}/ogre-1.9.0-fix-cflags.patch
+	patch -p0 -i ${srcdir}/ogre-endlessworld-fix.patch
+	patch -p1 -i ${srcdir}/ogre-freeimage-fix.patch
+	patch -p1 -i ${srcdir}/use-mingw-w64-directx.patch
+	patch -p1 -i ${srcdir}/mingw-w64-fix.patch
 }
 
 build() {
@@ -91,11 +92,11 @@ build() {
 	pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
 	export PREFIX_WIN=`pwd -W`
 	popd > /dev/null
-	
+
 	pushd ${MINGW_PREFIX} > /dev/null
 	export PREFIX_DEPS=`pwd -W`
 	popd > /dev/null
-	
+
 	case ${MINGW_CHOST} in
 		i686*)
 			local _march=pentium4 #i686
@@ -110,33 +111,33 @@ build() {
 	export CXXFLAGS="-O3 -pipe -march=${_march} -mtune=${_tune}"
 	export DXSDK_DIR=${PREFIX_DEPS}/${MINGW_CHOST}
 	mkdir ${srcdir}/build-${MINGW_CHOST} && cd ${srcdir}/build-${MINGW_CHOST}
-    ${MINGW_PREFIX}/bin/cmake.exe \
-	  -G"MSYS Makefiles" \
-	  -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX_WIN} \
-	  -DOGRE_DEPENDENCIES_DIR:PATH=${PREFIX_DEPS} \
-	  -DOGRE_INSTALL_TOOLS=ON \
-	  -DOGRE_COPY_DEPENDENCIES=OFF \
-	  -DOGRE_INSTALL_DEPENDENCIES=OFF \
-	  -DOGRE_BUILD_RENDERSYSTEM_D3D9=ON \
-	  -DOGRE_BUILD_RENDERSYSTEM_D3D11=OFF \
-	  -DCMAKE_BUILD_TYPE:STRING=${_buildtype} \
-	  -DFREETYPE_FT2BUILD_INCLUDE_DIR=${PREFIX_DEPS}/include/freetype2 \
-	  -DDirectX9_DXERR_LIBRARY=${PREFIX_DEPS}/${MINGW_CHOST}/lib/libdxerr9.a \
-	  ../${_realname}-${pkgver}
-	  
-    make
+	${MINGW_PREFIX}/bin/cmake.exe \
+		-G"MSYS Makefiles" \
+		-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX_WIN} \
+		-DOGRE_DEPENDENCIES_DIR:PATH=${PREFIX_DEPS} \
+		-DOGRE_INSTALL_TOOLS=ON \
+		-DOGRE_COPY_DEPENDENCIES=OFF \
+		-DOGRE_INSTALL_DEPENDENCIES=OFF \
+		-DOGRE_BUILD_RENDERSYSTEM_D3D9=ON \
+		-DOGRE_BUILD_RENDERSYSTEM_D3D11=OFF \
+		-DCMAKE_BUILD_TYPE:STRING=${_buildtype} \
+		-DFREETYPE_FT2BUILD_INCLUDE_DIR=${PREFIX_DEPS}/include/freetype2 \
+		-DDirectX9_DXERR_LIBRARY=${PREFIX_DEPS}/${MINGW_CHOST}/lib/libdxerr9.a \
+		../${_realname}-${pkgver}
+
+	make
 }
 
 package() {
 	cd "${srcdir}/build-${MINGW_CHOST}"
 	make -j1 install #DESTDIR="$pkgdir"
 	pushd ${pkgdir}${MINGW_PREFIX} > /dev/null
-	
+
 	mv bin/${_buildtype}/* bin/
 	rm -r bin/${_buildtype}
 	mv lib/${_buildtype}/* lib/
 	rm -r lib/${_buildtype}
-	  
+
 	sed -i "s|../../|../|g" \
 		bin/plugins.cfg \
 		bin/resources.cfg \
@@ -148,7 +149,7 @@ package() {
 	#rm -r media/CMakeFiles
 	#rm media/cmake_install.cmake
 	#rm media/Makefile
-		
+
 	#rm -r Docs/CMakeFiles
 	#rm Docs/cmake_install.cmake
 	#rm Docs/Makefile
