python-stestr: Drop python2 package

diff --git a/mingw-w64-python-stestr/PKGBUILD b/mingw-w64-python-stestr/PKGBUILD
--- a/mingw-w64-python-stestr/PKGBUILD
+++ b/mingw-w64-python-stestr/PKGBUILD
@@ -2,39 +2,27 @@
 
 _realname=stestr
 pkgbase=mingw-w64-python-${_realname}
-pkgname=("${MINGW_PACKAGE_PREFIX}-python2-${_realname}"  "${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
+pkgname=("${MINGW_PACKAGE_PREFIX}-python3-${_realname}")
 pkgver=2.5.1
-pkgrel=1
+pkgrel=2
 pkgdesc="A test runner runner similar to testrepository (mingw-w64)"
 arch=('any')
 url='https://stestr.readthedocs.io/en/latest/'
 license=('Apache')
-makedepends=("${MINGW_PACKAGE_PREFIX}-python2"
-             "${MINGW_PACKAGE_PREFIX}-python2-cliff"
-             "${MINGW_PACKAGE_PREFIX}-python2-fixtures"
-             "${MINGW_PACKAGE_PREFIX}-python2-future"
-             "${MINGW_PACKAGE_PREFIX}-python2-pbr"
-             "${MINGW_PACKAGE_PREFIX}-python2-setuptools"
-             "${MINGW_PACKAGE_PREFIX}-python2-six"
-             "${MINGW_PACKAGE_PREFIX}-python2-subunit"
-             "${MINGW_PACKAGE_PREFIX}-python2-testtools"
-             "${MINGW_PACKAGE_PREFIX}-python2-voluptuous"
-             "${MINGW_PACKAGE_PREFIX}-python2-yaml"
-             "${MINGW_PACKAGE_PREFIX}-python3"
-             "${MINGW_PACKAGE_PREFIX}-python3-cliff"
-             "${MINGW_PACKAGE_PREFIX}-python3-fixtures"
-             "${MINGW_PACKAGE_PREFIX}-python3-future"
-             "${MINGW_PACKAGE_PREFIX}-python3-pbr"
-             "${MINGW_PACKAGE_PREFIX}-python3-setuptools"
-             "${MINGW_PACKAGE_PREFIX}-python3-six"
-             "${MINGW_PACKAGE_PREFIX}-python3-subunit"
-             "${MINGW_PACKAGE_PREFIX}-python3-testtools"
-             "${MINGW_PACKAGE_PREFIX}-python3-voluptuous"
-             "${MINGW_PACKAGE_PREFIX}-python3-yaml"
-             )
-#checkdepends=('python-hacking' 'python2-hacking' 'python-sphinx' 'python2-sphinx' 'python-mock'
-#              'python2-mock' 'python-subunit2sql' 'python2-subunit2sql' 'python-coverage'
-#              'python2-coverage' 'python-ddt' 'python2-ddt')
+depends=("${MINGW_PACKAGE_PREFIX}-python3"
+         "${MINGW_PACKAGE_PREFIX}-python3-cliff"
+         "${MINGW_PACKAGE_PREFIX}-python3-fixtures"
+         "${MINGW_PACKAGE_PREFIX}-python3-future"
+         "${MINGW_PACKAGE_PREFIX}-python3-pbr"
+         "${MINGW_PACKAGE_PREFIX}-python3-six"
+         "${MINGW_PACKAGE_PREFIX}-python3-subunit"
+         "${MINGW_PACKAGE_PREFIX}-python3-testtools"
+         "${MINGW_PACKAGE_PREFIX}-python3-voluptuous"
+         "${MINGW_PACKAGE_PREFIX}-python3-yaml")
+makedepends=("${MINGW_PACKAGE_PREFIX}-python3-setuptools")
+#checkdepends=('python-hacking' 'python-sphinx' 'python-mock'
+#              'python-subunit2sql' 'python-coverage' 'python-ddt')
+install=${_realname}3-${CARCH}.install
 options=('staticlibs' 'strip' '!debug')
 source=("https://pypi.io/packages/source/s/stestr/stestr-${pkgver}.tar.gz")
 sha512sums=('f3f64448bd6782ab125e7d1094992bf1f9416cab8656c9f0bc800d00839b898000a04ffcf6010002f7c247ec06ca236389688ea67be6f3c1c979916455a03e28')
@@ -64,12 +52,12 @@ prepare() {
 #    apply_patch_with_msg 0001-A-really-important-fix.patch \
 #      0002-A-less-important-fix.patch
 #  popd 
-  for builddir in python{2,3}-build-${CARCH}; do
-    rm -rf ${builddir} | true
-    cp -r "${_realname}-${pkgver}" "${builddir}"
-  done
+
+  rm -rf python3-build-${CARCH} | true
+  cp -r "${_realname}-${pkgver}" "python3-build-${CARCH}"
+
   # Set version for setuptools_scm
-  export SETUPTOOLS_SCM_PRETEND_VERSION=$pkgver
+  export SETUPTOOLS_SCM_PRETEND_VERSION=${pkgver}
 }
 
 # Note that build() is sometimes skipped because it's done in 
@@ -77,41 +65,20 @@ prepare() {
 # but sometimes, you want to do a check before install which would
 # also trigger the build.
 build() {
-  for pver in {2,3}; do  
-    msg "Python ${pver} build for ${CARCH}"  
-    cd "${srcdir}/python${pver}-build-${CARCH}"
-    ${MINGW_PREFIX}/bin/python${pver} setup.py build
-  done  
+  msg "Python 3 build for ${CARCH}"  
+  cd "${srcdir}/python3-build-${CARCH}"
+  ${MINGW_PREFIX}/bin/python3 setup.py build
 }
 
 #check() {
-#  for pver in {2,3}; do
-#    msg "Python ${pver} test for ${CARCH}"
-#    cd "${srcdir}/python${pver}-build-${CARCH}"
-#    export PYTHONPATH="$PWD/tmp_install/usr/lib/python3.7/site-packages"
-#    export PATH="$PWD/tmp_install/usr/bin:$PATH"
-#    stestr run || warning "Tests failed"
-
-#  done
+#  msg "Python 3 test for ${CARCH}"
+#  cd "${srcdir}/python3-build-${CARCH}"
+#  export PYTHONPATH="$PWD/tmp_install/usr/lib/python3.8/site-packages"
+#  export PATH="$PWD/tmp_install/usr/bin:$PATH"
+#  stestr run || warning "Tests failed"
 #}
 
-package_python3-stestr() {
-  depends=("${MINGW_PACKAGE_PREFIX}-python3"
-           "${MINGW_PACKAGE_PREFIX}-python3-cliff"
-           "${MINGW_PACKAGE_PREFIX}-python3-fixtures"
-           "${MINGW_PACKAGE_PREFIX}-python3-future"
-           "${MINGW_PACKAGE_PREFIX}-python3-pbr"
-           "${MINGW_PACKAGE_PREFIX}-python3-six"
-           "${MINGW_PACKAGE_PREFIX}-python3-subunit"
-           "${MINGW_PACKAGE_PREFIX}-python3-testtools"
-           "${MINGW_PACKAGE_PREFIX}-python3-voluptuous"
-           "${MINGW_PACKAGE_PREFIX}-python3-yaml")
-
-  #This package install is needed for .fixups with .EXE's 
-  #in the bit directory.  The install files "python-exe-installs"
-  #and should be renamed to your _realname .
-  install=${_realname}3-${CARCH}.install
-
+package) {
   cd "${srcdir}/python3-build-${CARCH}"
   MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=" \
   ${MINGW_PREFIX}/bin/python3 setup.py install --prefix=${MINGW_PREFIX} \
@@ -119,77 +86,14 @@ package_python3-stestr() {
 
   install -Dm644 LICENSE "${pkgdir}${MINGW_PREFIX}/share/licenses/python3-${_realname}/LICENSE"
 
-# This entire section should be removed if the package does NOT install
-# anything in the /mingw*/bin directory.
-### begin section ###
+  # This entire section should be removed if the package does NOT install
+  # anything in the /mingw*/bin directory.
+  ### begin section ###
   local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
   # fix python command in files
   for _f in "${pkgdir}${MINGW_PREFIX}"/bin/*.py; do
     sed -e "s|/usr/bin/env |${MINGW_PREFIX}|g" \
         -e "s|${PREFIX_WIN}|${MINGW_PREFIX}|g" -i ${_f}
   done
-#### end section ####
-}
-
-package_python2-stestr() {
-  depends=("${MINGW_PACKAGE_PREFIX}-python2"
-           "${MINGW_PACKAGE_PREFIX}-python2-cliff"
-           "${MINGW_PACKAGE_PREFIX}-python2-fixtures"
-           "${MINGW_PACKAGE_PREFIX}-python2-future"
-           "${MINGW_PACKAGE_PREFIX}-python2-pbr"
-           "${MINGW_PACKAGE_PREFIX}-python2-six"
-           "${MINGW_PACKAGE_PREFIX}-python2-subunit"
-           "${MINGW_PACKAGE_PREFIX}-python2-testtools"
-           "${MINGW_PACKAGE_PREFIX}-python2-voluptuous"
-           "${MINGW_PACKAGE_PREFIX}-python2-yaml")
-  #This package install is needed for .fixups with .EXE's 
-  #in the bit directory.  The install files "python-exe-installs"
-  #and should be renamed to your _realname
-  install=${_realname}2-${CARCH}.install
-
-  cd "${srcdir}/python2-build-${CARCH}"
-  MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=" \
-  ${MINGW_PREFIX}/bin/python2 setup.py install --prefix=${MINGW_PREFIX} \
-    --root="${pkgdir}" --optimize=1 --skip-build
-
-  install -Dm644 LICENSE "${pkgdir}${MINGW_PREFIX}/share/licenses/python2-${_realname}/LICENSE"
-
-# This entire section should be removed if the package does NOT install
-# anything in the /mingw*/bin directory. 
-### begin section ###
-  local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
-  # fix python command in files
-  for _f in "${pkgdir}${MINGW_PREFIX}"/bin/*.py; do
-    sed -e "s|/usr/bin/env |${MINGW_PREFIX}|g" \
-        -e "s|${PREFIX_WIN}|${MINGW_PREFIX}|g" -i ${_f}
-  done
-
-# for Python2 packages, you want to rename some stuff from the bin directory 
-# with the 2 suffix like in the mingw-w64-python-pygments package to avoid
-# conflicts when installing both the Python2 and Python3 packages
-  for f in stestr; do
-    mv "${pkgdir}${MINGW_PREFIX}"/bin/${f}{,2}.exe
-    if [ -f "${pkgdir}${MINGW_PREFIX}"/bin/${f}.exe.manifest ]; then
-      mv "${pkgdir}${MINGW_PREFIX}"/bin/${f}{,2}.exe.manifest
-      sed -e "s|${f}|${f}2|g" -i "${pkgdir}${MINGW_PREFIX}"/bin/${f}2.exe.manifest
-    fi
-    mv "${pkgdir}${MINGW_PREFIX}"/bin/${f}{,2}-script.py
-  done
-#### end section ####
-}
-
-package_mingw-w64-i686-python2-stestr() {
-  package_python2-stestr
-}
-
-package_mingw-w64-i686-python3-stestr() {
-  package_python3-stestr
-}
-
-package_mingw-w64-x86_64-python2-stestr() {
-  package_python2-stestr
-}
-
-package_mingw-w64-x86_64-python3-stestr() {
-  package_python3-stestr
+  #### end section ####
 }
