litehtml: update to 0.10 (#30015)
* litehtml: update to 0.10

* qt-creator: use bundled litehtml for now.

qlitehtml is not compatible with litehtml 0.10

---------

Co-authored-by: Christoph Reiter <reiter.christoph@gmail.com>
Co-authored-by: مهدي شينون (Mehdi Chinoune) <mehdi.chinoune@hotmail.com>

diff --git a/mingw-w64-litehtml/PKGBUILD b/mingw-w64-litehtml/PKGBUILD
--- a/mingw-w64-litehtml/PKGBUILD
+++ b/mingw-w64-litehtml/PKGBUILD
@@ -3,8 +3,8 @@
 _realname=litehtml
 pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
-pkgver=0.9
-pkgrel=2
+pkgver=0.10
+pkgrel=1
 pkgdesc="Fast and lightweight HTML/CSS rendering engine (mingw-w64)"
 arch=('any')
 mingw_arch=('mingw64' 'ucrt64' 'clang64' 'clangarm64')
@@ -16,12 +16,11 @@ depends=("${MINGW_PACKAGE_PREFIX}-cc-libs"
 makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
              "${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-ninja")
+checkdepends=("${MINGW_PACKAGE_PREFIX}-gtk3")
 source=("https://github.com/litehtml/litehtml/archive/v$pkgver/$_realname-$pkgver.tar.gz")
-sha256sums=('ef957307da15b1258a70961942840bcf54225a8d75315dcbc156186eba35b1a7')
+sha256sums=('7700eced92847d34ad9846b138cf195a9c974b519be70de58797880ae9da649e')
 
 build() {
-  mkdir -p "${srcdir}/build-${MSYSTEM}" && cd "${srcdir}/build-${MSYSTEM}"
-
   declare -a extra_config
   if check_option "debug" "n"; then
     extra_config+=("-DCMAKE_BUILD_TYPE=Release")
@@ -30,7 +29,7 @@ build() {
   fi
 
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
-    "${MINGW_PREFIX}"/bin/cmake.exe \
+    cmake \
       -GNinja \
       -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" \
       "${extra_config[@]}" \
@@ -38,15 +37,21 @@ build() {
       -DCMAKE_DLL_NAME_WITH_SOVERSION=ON \
       -DEXTERNAL_GUMBO=ON \
       -DLITEHTML_BUILD_TESTING=OFF \
-      ../${_realname}-${pkgver}
+      -S ${_realname}-${pkgver} \
+      -B "build-${MSYSTEM}"
 
-  "${MINGW_PREFIX}"/bin/cmake.exe --build .
+  cmake --build "build-${MSYSTEM}"
 }
 
-package() {
-  cd "${srcdir}/build-${MSYSTEM}"
+# Currently tests build failed due to missing `-lstdc++fs`
+# check() {
+#   cmake -DLITEHTML_BUILD_TESTING=ON -S ${_realname}-${pkgver} -B "build-${MSYSTEM}"
+#   cmake --build "build-${MSYSTEM}"
+#   ctest --test-dir "build-${MSYSTEM}" --output-on-failure || true
+# }
 
-  DESTDIR="${pkgdir}" "${MINGW_PREFIX}"/bin/cmake.exe --install .
+package() {
+  DESTDIR="${pkgdir}" cmake --install "build-${MSYSTEM}"
 
   # Don't search for non-existant gumbo cmake config
   sed -e '/gumbo/d' -i "${pkgdir}${MINGW_PREFIX}"/lib/cmake/litehtml/litehtmlConfig.cmake
