vtk: update to 9.1.0

diff --git a/mingw-w64-vtk/PKGBUILD b/mingw-w64-vtk/PKGBUILD
--- a/mingw-w64-vtk/PKGBUILD
+++ b/mingw-w64-vtk/PKGBUILD
@@ -4,8 +4,8 @@
 _realname=vtk
 pkgbase="mingw-w64-${_realname}"
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
-pkgver=8.2.0
-pkgrel=11
+pkgver=9.1.0
+pkgrel=1
 pkgdesc="A software system for 3D computer graphics, image processing and visualization (mingw-w64)"
 arch=('any')
 mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32')
@@ -13,81 +13,108 @@ url="https://www.vtk.org/"
 license=("BSD")
 depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
          "${MINGW_PACKAGE_PREFIX}-double-conversion"
-         "${MINGW_PACKAGE_PREFIX}-expat"
-         "${MINGW_PACKAGE_PREFIX}-ffmpeg"
-         "${MINGW_PACKAGE_PREFIX}-fontconfig"
-         "${MINGW_PACKAGE_PREFIX}-freetype"
-         "${MINGW_PACKAGE_PREFIX}-glew"
-         "${MINGW_PACKAGE_PREFIX}-gl2ps"
-         "${MINGW_PACKAGE_PREFIX}-hdf5"
+         "${MINGW_PACKAGE_PREFIX}-fmt"
          "${MINGW_PACKAGE_PREFIX}-intel-tbb"
-         "${MINGW_PACKAGE_PREFIX}-jsoncpp"
-         "${MINGW_PACKAGE_PREFIX}-libjpeg"
-        #  "${MINGW_PACKAGE_PREFIX}-libharu"
-         "${MINGW_PACKAGE_PREFIX}-libpng"
-         "${MINGW_PACKAGE_PREFIX}-libogg"
-         "${MINGW_PACKAGE_PREFIX}-libtheora"
-         "${MINGW_PACKAGE_PREFIX}-libtiff"
-         "${MINGW_PACKAGE_PREFIX}-libxml2"
+         "${MINGW_PACKAGE_PREFIX}-libwinpthread-git"
          "${MINGW_PACKAGE_PREFIX}-lz4"
-         "${MINGW_PACKAGE_PREFIX}-netcdf"
-        #  "${MINGW_PACKAGE_PREFIX}-proj"
+         $([[ ${MINGW_PACKAGE_PREFIX} != *-clang-* ]] || echo "${MINGW_PACKAGE_PREFIX}-openmp")
          "${MINGW_PACKAGE_PREFIX}-pugixml"
-         "${MINGW_PACKAGE_PREFIX}-sqlite3"
          "${MINGW_PACKAGE_PREFIX}-xz"
-         "${MINGW_PACKAGE_PREFIX}-zlib"
-         )
+         "${MINGW_PACKAGE_PREFIX}-zlib")
 makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
              "${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-ninja"
+             "${MINGW_PACKAGE_PREFIX}-adios2"
              "${MINGW_PACKAGE_PREFIX}-boost"
-             "${MINGW_PACKAGE_PREFIX}-gdal"
+             "${MINGW_PACKAGE_PREFIX}-cgns"
+             "${MINGW_PACKAGE_PREFIX}-cli11"
              "${MINGW_PACKAGE_PREFIX}-eigen3"
+             "${MINGW_PACKAGE_PREFIX}-expat"
+             "${MINGW_PACKAGE_PREFIX}-ffmpeg"
+             "${MINGW_PACKAGE_PREFIX}-fontconfig"
+             "${MINGW_PACKAGE_PREFIX}-freetype"
+             "${MINGW_PACKAGE_PREFIX}-gdal"
+             "${MINGW_PACKAGE_PREFIX}-gl2ps"
+             "${MINGW_PACKAGE_PREFIX}-glew"
+             "${MINGW_PACKAGE_PREFIX}-hdf5"
+             "${MINGW_PACKAGE_PREFIX}-jsoncpp"
+             "${MINGW_PACKAGE_PREFIX}-libharu"
+             "${MINGW_PACKAGE_PREFIX}-libjpeg"
+             "${MINGW_PACKAGE_PREFIX}-liblas"
              "${MINGW_PACKAGE_PREFIX}-libmariadbclient"
+             "${MINGW_PACKAGE_PREFIX}-libpng"
+             "${MINGW_PACKAGE_PREFIX}-libogg"
+             "${MINGW_PACKAGE_PREFIX}-libtheora"
+             "${MINGW_PACKAGE_PREFIX}-libtiff"
+             "${MINGW_PACKAGE_PREFIX}-libxml2"
+             "${MINGW_PACKAGE_PREFIX}-netcdf"
+             "${MINGW_PACKAGE_PREFIX}-openslide"
+             "${MINGW_PACKAGE_PREFIX}-openturns"
+             "${MINGW_PACKAGE_PREFIX}-openvdb"
+             "${MINGW_PACKAGE_PREFIX}-openvr"
+             "${MINGW_PACKAGE_PREFIX}-pdal"
+             # "${MINGW_PACKAGE_PREFIX}-pegtl" https://gitlab.kitware.com/vtk/vtk/-/issues/18151
              "${MINGW_PACKAGE_PREFIX}-postgresql"
+             "${MINGW_PACKAGE_PREFIX}-proj"
              "${MINGW_PACKAGE_PREFIX}-python"
-             "${MINGW_PACKAGE_PREFIX}-qt5-base"
-             "${MINGW_PACKAGE_PREFIX}-qt5-winextras"
-             "${MINGW_PACKAGE_PREFIX}-qt5-tools"
-             "${MINGW_PACKAGE_PREFIX}-tk"
+             "${MINGW_PACKAGE_PREFIX}-qt5-declarative"
+             "${MINGW_PACKAGE_PREFIX}-sqlite3"
+             # "${MINGW_PACKAGE_PREFIX}-tk"
+             "${MINGW_PACKAGE_PREFIX}-unixodbc"
+             "${MINGW_PACKAGE_PREFIX}-utf8cpp"
              )
-optdepends=("${MINGW_PACKAGE_PREFIX}-boost: InfovisBoost and InfovisBoostGraphAlgorithms modules"
-            "${MINGW_PACKAGE_PREFIX}-gdal"
-            "${MINGW_PACKAGE_PREFIX}-libmariadbclient: interface to MariaDB"
+optdepends=("${MINGW_PACKAGE_PREFIX}-adios2: I/O ADIOS2"
+            "${MINGW_PACKAGE_PREFIX}-boost: InfovisBoost and InfovisBoostGraphAlgorithms modules"
+            "${MINGW_PACKAGE_PREFIX}-cgns: CGNS Reader"
+            "${MINGW_PACKAGE_PREFIX}-expat: XML Parser"
+            "${MINGW_PACKAGE_PREFIX}-ffmpeg: I/O FFMPEG"
+            "${MINGW_PACKAGE_PREFIX}-fontconfig: Freetype/Fontconfig Rendering"
+            "${MINGW_PACKAGE_PREFIX}-freetype: Freetype Rendering"
+            "${MINGW_PACKAGE_PREFIX}-gdal: I/O GDAL"
+            "${MINGW_PACKAGE_PREFIX}-gl2ps: PS Rendering"
+            "${MINGW_PACKAGE_PREFIX}-glew: OpenGL2 Rendering"
+            "${MINGW_PACKAGE_PREFIX}-hdf5: I/O HDF5"
+            "${MINGW_PACKAGE_PREFIX}-jsoncpp: IOGeometry"
+            "${MINGW_PACKAGE_PREFIX}-libharu: PDF Rendering"
+            "${MINGW_PACKAGE_PREFIX}-libjpeg: I/O Images"
+            "${MINGW_PACKAGE_PREFIX}-liblas"
+            "${MINGW_PACKAGE_PREFIX}-libmariadbclient: interface to MySQL/MariaDB"
+            "${MINGW_PACKAGE_PREFIX}-libpng: I/O Images"
+            "${MINGW_PACKAGE_PREFIX}-libogg: I/O OGG and Theora"
+            "${MINGW_PACKAGE_PREFIX}-libtheora: I/O OGG and Theora"
+            "${MINGW_PACKAGE_PREFIX}-libtiff: I/O Images"
+            "${MINGW_PACKAGE_PREFIX}-libxml2: Infovis"
+            "${MINGW_PACKAGE_PREFIX}-netcdf: I/O netCDF"
+            "${MINGW_PACKAGE_PREFIX}-openslide: DomainsMicroscopy"
+            "${MINGW_PACKAGE_PREFIX}-openturns"
+            "${MINGW_PACKAGE_PREFIX}-openvdb: I/O OpenVDB"
+            "${MINGW_PACKAGE_PREFIX}-openvr: OpenVR Rendering"
+            "${MINGW_PACKAGE_PREFIX}-pdal: I/O PDAL"
             "${MINGW_PACKAGE_PREFIX}-postgresql: interface to PostgreSQL"
+            "${MINGW_PACKAGE_PREFIX}-proj: GEOVis"
             "${MINGW_PACKAGE_PREFIX}-python: Python bindings"
             "${MINGW_PACKAGE_PREFIX}-python-matplotlib: Matplotlib renderer"
-            "${MINGW_PACKAGE_PREFIX}-tk: TCL bindings, Python Tk widgets"
-            "${MINGW_PACKAGE_PREFIX}-qt-base"
-            "${MINGW_PACKAGE_PREFIX}-qt-winextras")
+            "${MINGW_PACKAGE_PREFIX}-qt5-base: Qt Rendering"
+            "${MINGW_PACKAGE_PREFIX}-qt5-declarative: Qt Qml plugin"
+            "${MINGW_PACKAGE_PREFIX}-sqlite3: Interface to SQL"
+            # "${MINGW_PACKAGE_PREFIX}-tk: TCL bindings, Python Tk widgets"
+            "${MINGW_PACKAGE_PREFIX}-unixodbc")
 source=(https://www.vtk.org/files/release/${pkgver%.*}/VTK-${pkgver}.tar.gz
-        "001-vtk-mingw-w64.patch"
-        "004-fix-linking-rendering-tk.patch"
-        "005-remove-bogus-stdint-check.patch"
-        "006-win7-defines-guard.patch"
-        "007-fix-linking-movie.patch"
-        "008-fix-python-modules-path.patch"
-        "020-python38-compat.patch"
-        "030-pugixml.patch"
-        "031-fno-common.patch"
-        "032-freetype-2.10.3-provide-FT_CALLBACK_DEF.patch"
-        "033-qt-5.15.patch"
-        "034-no-dllexport-with-delete.patch"
-        "https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6178.patch")
-sha256sums=('34c3dc775261be5e45a8049155f7228b6bd668106c72a3c435d95730d17d57bb'
-            'db3163012fc7d90f6ffd8300a7a306a609e7c69a88a1dcfb9cb5b5df4391e3ad'
-            '7f428a9c15b2dfc23fff2a19a11c48a628c9b52f82ec0d1dca37d0a5cffc9aef'
-            '769e28e106e612671433eb2f84ab6c0c9ef676109d690f6fe330641631c1fd2b'
-            '087d570104d2ae7f00437897e88225a1eb904b125e3a27bb9392ddf8ef068f6c'
-            'ec39407b6174c9b1326389b4badf1c0c377d74a6dd2c53caf983613fafe43c81'
-            'b6d6f4de0e58251843dec3dfad0ae5d5308c66ab8e55a56eeb3855cd699b02f3'
-            '1d9a3227feb50d08cb507d2a750b480f15eb1819f15c5b88474ba944c51f256a'
-            'cbcc8a0c81450e015c2ce4035f2f128956d20a22be581199446c4a72c0396190'
-            'a4597f0410bea856b06d023d9db7d2661b505eec110f4beccc155f6aa2c593f7'
-            'aa43d6b702e3e1bca2cb8560c1c7e6ce5681cef8a89e9b6442f8037bc295c21c'
-            'de1d2088c54bc7fdd494cb8a90464d2f53dc7cabddcd0415d9fb8cc4de448d0e'
-            '902ec3d23551de899a0682af88acc61257242fb5f474470884c3468d86a0d9f8'
-            '49574bb914e2564b21ab0fb23cadcccd7dd323ae7f0f26f64fd6346c3db14cd7')
+        "001-no-strptime-with-clang.patch"
+        "002-fix-python-modules-path.patch"
+        "003-fix-find-odbc-mingw.patch"
+        "004-Build-GUISupportMFC-only-with-MSVC.patch"
+        "005-fix-build-vtkm-mingw.patch"
+        "006-link-to-pdalcpp.patch"
+        "007-dll-export-some-functions.patch")
+sha256sums=('8fed42f4f8f1eb8083107b68eaa9ad71da07110161a3116ad807f43e5ca5ce96'
+            'df2eef7c8533ebcf9926a8bab309531253387849a1fc2e797fb01c0638aee094'
+            'a2396e3aecc3c8ade391496f7a7ce4efc7f6eb53911ddd1b473f2230e1b22161'
+            '7d22fcfb108b7edb0ceb050378461e9987a330636a1317dfca68638962815948'
+            '5b39f9aa28f169d1f35b42cf5ae8433eb4ea6f8bee4894b7dcd63d2ba622b3e5'
+            '353d046a96fe6cb3019857132676671b60e18d02e4bba43e79a21673e4d5735f'
+            'af98e72a0d64af3fa755929e724e900faa9ab466917fc24084026512f02399e4'
+            'bac0c76884095fd3e15553e0b6f55c373acef65a0f43baf2b503e13693ba8f48')
 
 # Helper macros to help make tasks easier #
 apply_patch_with_msg() {
@@ -101,83 +128,72 @@ apply_patch_with_msg() {
 prepare() {
   cd "${srcdir}/${_realname}-${pkgver}"
 
+  # We have a patched libharu
+  sed -i "s|2.4.0|2.3.0|" ThirdParty/libharu/CMakeLists.txt
+
+  # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9015
   apply_patch_with_msg \
-    001-vtk-mingw-w64.patch \
-    004-fix-linking-rendering-tk.patch
-  # it will find stdint from msys2-runtime-devel, but that's useless
+    001-no-strptime-with-clang.patch
+  # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9016
   apply_patch_with_msg \
-    005-remove-bogus-stdint-check.patch
+    002-fix-python-modules-path.patch
+  # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9019
   apply_patch_with_msg \
-    006-win7-defines-guard.patch \
-    007-fix-linking-movie.patch \
-    008-fix-python-modules-path.patch \
-    020-python38-compat.patch \
-    030-pugixml.patch \
-    031-fno-common.patch \
-    032-freetype-2.10.3-provide-FT_CALLBACK_DEF.patch \
-    033-qt-5.15.patch \
-    034-no-dllexport-with-delete.patch \
-    6178.patch
+    003-fix-find-odbc-mingw.patch
+  # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9024
+  apply_patch_with_msg \
+    004-Build-GUISupportMFC-only-with-MSVC.patch
+  apply_patch_with_msg \
+    005-fix-build-vtkm-mingw.patch \
+    006-link-to-pdalcpp.patch
+  # Succeed with Clang but failed with GCC!
+  if [[ ${MINGW_PACKAGE_PREFIX} == *-clang-* ]]; then
+    apply_patch_with_msg \
+      007-dll-export-some-functions.patch
+  fi
 }
 
 build() {
   [[ -d ${srcdir}/build-${MSYSTEM} ]] && rm -rf ${srcdir}/build-${MSYSTEM}
   mkdir -p ${srcdir}/build-${MSYSTEM} && cd ${srcdir}/build-${MSYSTEM}
 
-  CFLAGS+=" ${CPPFLAGS}"
-  CXXFLAGS+=" ${CPPFLAGS} -std=gnu++11 -Wno-ignored-attributes -Wno-deprecated-declarations"
-  [[ "$CARCH" = 'i686' ]] && {
-    _cmakeopts=('-DVTK_USE_64BIT_IDS=OFF')
-  }
-  [[ "$CARCH" = 'x86_64' ]] && {
-    _cmakeopts=('-DVTK_USE_64BIT_IDS=ON')
-  }
+  declare -a extra_config
+  if check_option "debug" "n"; then
+    extra_config+=("-DCMAKE_BUILD_TYPE=Release")
+  else
+    extra_config+=("-DCMAKE_BUILD_TYPE=Debug")
+  fi
 
-  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=;-DVTK_INSTALL_QT_PLUGIN_DIR=;-DVTK_INSTALL_TCL_DIR=" \
+  CFLAGS+=" ${CPPFLAGS}"
+  CXXFLAGS+=" ${CPPFLAGS} -Wno-ignored-attributes -Wno-deprecated-declarations"
+
+  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
   ${MINGW_PREFIX}/bin/cmake \
     -Wno-dev \
     -G"Ninja" \
+    ${extra_config[@]} \
     -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_RC_FLAGS=--use-temp-file \
+    -DCMAKE_INSTALL_LICENSEDIR=share/licenses/vtk \
     -DBUILD_SHARED_LIBS=ON \
-    -DPYTHON_EXECUTABLE="${MINGW_PREFIX}/bin/python.exe" \
-    -DBUILD_DOCUMENTATION=OFF \
-    -DBUILD_EXAMPLES=OFF \
-    -DBUILD_TESTING=OFF \
-    -DVTK_Group_Imaging=ON \
-    -DVTK_Group_MPI=OFF \
-    -DVTK_Group_Qt=ON \
-    -DVTK_Group_Rendering=ON \
-    -DVTK_Group_StandAlone=ON \
-    -DVTK_Group_Tk=ON \
-    -DVTK_Group_Views=ON \
-    -DVTK_Group_Web=OFF \
-    -DVTK_USE_SYSTEM_LIBRARIES=ON \
-    -DVTK_USE_SYSTEM_LIBPROJ=OFF \
-    -DVTK_USE_SYSTEM_LIBHARU=OFF \
-    -DModule_vtkIOFFMPEG=ON \
-    -DModule_vtkIOMySQL=ON \
-    -DModule_vtkInfovisBoost=ON \
-    -DModule_vtkInfovisBoostGraphAlgorithms=ON \
-    -DModule_vtkIOGDAL=ON \
-    -DModule_vtkIOODBC=OFF \
-    -DModule_vtkIOPostgreSQL=ON \
-    -DModule_vtkPythonInterpreter=ON \
-    -DModule_vtkFiltersReebGraph=ON \
-    -DModule_vtkRenderingFreeTypeFontConfig=ON \
-    -DModule_vtkRenderingMatplotlib=ON \
-    -DVTK_INSTALL_QT_PLUGIN_DIR="${MINGW_PREFIX}/share/qt5/plugins/designer" \
-    -DVTK_INSTALL_TCL_DIR="${MINGW_PREFIX}/lib/vtk-${pkgver%.*}" \
-    -DVTK_LEGACY_REMOVE=OFF \
+    -DPython3_EXECUTABLE="${MINGW_PREFIX}/bin/python.exe" \
+    -DVTK_BUILD_TESTING=OFF \
+    -DVTK_VERSIONED_INSTALL=OFF \
+    -DVTK_BUILD_ALL_MODULES=ON \
+    -DVTK_GROUP_ENABLE_MPI=NO \
+    -DVTK_GROUP_ENABLE_Web=NO \
+    -DVTK_MODULE_ENABLE_VTK_vtkm=NO \
+    -DVTK_USE_EXTERNAL=ON \
+    -DVTK_MODULE_USE_EXTERNAL_VTK_exprtk=OFF \
+    -DVTK_MODULE_USE_EXTERNAL_VTK_ioss=OFF \
+    -DVTK_MODULE_USE_EXTERNAL_VTK_pegtl=OFF \
     -DVTK_WRAP_JAVA=OFF \
     -DVTK_WRAP_PYTHON=ON \
-    -DVTK_QT_VERSION=5 \
     -DVTK_SMP_IMPLEMENTATION_TYPE=TBB \
+    -DVTK_SMP_ENABLE_SEQUENTIAL=ON \
+    -DVTK_SMP_ENABLE_STDTHREAD=ON \
+    -DVTK_SMP_ENABLE_OPENMP=ON \
     -DVTK_USE_VIDEO_FOR_WINDOWS=ON \
-    -DMYSQL_INCLUDE_DIRECTORIES="${MINGW_PREFIX}/include/mariadb" \
-    -DMYSQL_LIBRARY="${MINGW_PREFIX}/lib/libmariadb.dll.a" \
-    ${_cmakeopts[@]} \
+    -DVTK_ENABLE_OSPRAY=OFF \
     ../${_realname}-${pkgver}
 
   ${MINGW_PREFIX}/bin/cmake --build .
@@ -186,16 +202,4 @@ build() {
 package() {
   cd "${srcdir}/build-${MSYSTEM}"
   DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/cmake --install .
-
-  local PREFIX_DEPS=$(cygpath -am ${MINGW_PREFIX})
-
-  pushd "${pkgdir}${MINGW_PREFIX}/lib/cmake/${_realname}-${pkgver%.*}" > /dev/null
-  sed -s 's|Qt5::|Qt5|g' -i ./VTKTargets*.cmake
-  sed -s "s|${PREFIX_DEPS}|\${_IMPORT_PREFIX}|g" -i ./VTKTargets.cmake
-  find . -name '*.cmake' -exec \
-    sed -s "s|${PREFIX_DEPS}|\${VTK_INSTALL_PREFIX}|g" -i {} \;
-  popd > /dev/null
-
-  install -Dm644 "${srcdir}/${_realname}-${pkgver}/Copyright.txt" \
-    "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/Copyright.txt"
 }
