rust: build with PGO

diff --git a/mingw-w64-rust/PKGBUILD b/mingw-w64-rust/PKGBUILD
--- a/mingw-w64-rust/PKGBUILD
+++ b/mingw-w64-rust/PKGBUILD
@@ -14,14 +14,12 @@ rust_dist_server=https://static.rust-lang.org/dist
 _realname=rust
 pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
-         $([[ ${CARCH} == i686 ]] || echo \
-         "${MINGW_PACKAGE_PREFIX}-rust-wasm" \
-         "${MINGW_PACKAGE_PREFIX}-rust-src"))
+         "${MINGW_PACKAGE_PREFIX}-rust-wasm")
 pkgver=1.86.0
-pkgrel=2
+pkgrel=3
 pkgdesc="Systems programming language focused on safety, speed and concurrency (mingw-w64)"
 arch=('any')
-mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clangarm64')
+mingw_arch=('mingw64' 'ucrt64' 'clang64' 'clangarm64')
 url="https://www.rust-lang.org/"
 msys2_repository_url="https://github.com/rust-lang/rust"
 msys2_references=(
@@ -30,49 +28,58 @@ msys2_references=(
 )
 license=('spdx:Apache-2.0 AND MIT')
 makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
+             "${MINGW_PACKAGE_PREFIX}-ccache"
+             "${MINGW_PACKAGE_PREFIX}-compiler-rt"
              "${MINGW_PACKAGE_PREFIX}-clang"
              "${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-curl"
              "${MINGW_PACKAGE_PREFIX}-libffi"
              "${MINGW_PACKAGE_PREFIX}-libssh2"
+             "${MINGW_PACKAGE_PREFIX}-lld"
              "${MINGW_PACKAGE_PREFIX}-llvm"
              "${MINGW_PACKAGE_PREFIX}-openssl"
              "${MINGW_PACKAGE_PREFIX}-pkgconf"
              "${MINGW_PACKAGE_PREFIX}-python"
              $([[ "$_bootstrapping" == "no" ]] && echo "${MINGW_PACKAGE_PREFIX}-rust")
-             $([[ ${CARCH} == i686 ]] || echo "${MINGW_PACKAGE_PREFIX}-wasi-libc ${MINGW_PACKAGE_PREFIX}-wasm-component-ld")
+             "${MINGW_PACKAGE_PREFIX}-wasi-libc"
+             "${MINGW_PACKAGE_PREFIX}-wasm-component-ld"
              "${MINGW_PACKAGE_PREFIX}-zstd"
-             "${MINGW_PACKAGE_PREFIX}-zlib")
+             "${MINGW_PACKAGE_PREFIX}-zlib"
+             'git')
 source=("${rust_dist_server}/${_realname}c-${pkgver}-src.tar.gz"{,.asc}
+        "cc-1.2.19.tar.gz::https://crates.io/api/v1/crates/cc/1.2.19/download"
+        "cc-1.1.10.tar.gz::https://crates.io/api/v1/crates/cc/1.1.10/download"
+        "rustc-perf::git+https://github.com/rust-lang/rustc-perf.git#commit=e22e08623a349b13a3296971a05394d44f769744"
         "config.toml"
-        "0001-rustc-llvm-fix-libs.patch"
         "0004-compiler-Use-wasm-ld-for-wasm-targets.patch"
         "0008-disable-self-contained-for-gnu-targets.patch"
-        # remove after 1.87.0 release
-        "0009-support-LLVM20.patch")
+        "0012-rustc-perf-update-cc.patch"
+        "0013-deps-checksums.patch"
+        # various backports to make opt-dist work in our environment
+        "https://patch-diff.githubusercontent.com/raw/rust-lang/rust/pull/137676.patch"
+        "https://patch-diff.githubusercontent.com/raw/rust-lang/rust/pull/139757.patch"
+        "https://patch-diff.githubusercontent.com/raw/rust-lang/rust/pull/139894.patch"
+        "139931.patch"
+        "https://patch-diff.githubusercontent.com/raw/rust-lang/rust/pull/139962.patch")
 noextract=(${_realname}c-${pkgver}-src.tar.gz)
 sha256sums=('022a27286df67900a044d227d9db69d4732ec3d833e4ffc259c4425ed71eed80'
             'SKIP'
-            '28c3e6d712d541b301e1ae5c9e9385996afd8b2e4fa34b86393c0ac79cec15e7'
-            '7cb1773c288ffb1c1e751edc49b1890c84bf9c362742bc5225d19d474edb73a0'
+            '8e3a13707ac958681c13b39b458c073d0d9bc8a22cb1b2f4c8e55eb72c13f362'
+            'e9e8aabfac534be767c909e0690571677d49f41bd8465ae876fe043d52ba5292'
+            '9825f944b5a11bc01528dadc2c85f2589bbd5ba44295849a33c32792f52ebd61'
+            'b856b424c68cb74dd6b3e0c3b3f50c8d190d687890d9a0521a438dac56ec5dfd'
             '56882f1a0f1404c10c7726d6cc37444f2b343e72b969badfcb43760f80db0f32'
             '98bc3f2bd7371a5b8d14fd7b03bf05574e206d1d9e52bcfbe66d71398504da3c'
-            'c18e16c0575ab01576e8cf4596cf3c779805da1a1e342b274d4424f6decbfda5')
+            '32467f8cd70a5ba4b94278c5da1a55e660507b814a7b897171a075e5154fa301'
+            'acc6bcc3adc79c6303fb3ce678aeb8bf7ebef7a07f347b6a89bb144a565ca847'
+            'f7eb5c94ad30cdebc7ba5ff34a675393842893d9901485efe91b54ddb4f06817'
+            '22c1c1c7f5bd136d67f6ca2a0fd11e0156331721078ad7ae95122e63362dd7e7'
+            '103cefc1d2de6a3ed5ba673523a01e957ee21926ca713ed262443e9139c4d869'
+            'bb8c51b68cf50669994d95c708e45d6d7d54948631fd7f9a8aeda40938c8eb75'
+            '6213e9b9b1e83d5543b2999c15be5dd357331985b059ccae297d7af6499dbf53')
 validpgpkeys=('108F66205EAEB0AAA8DD5E1C85AB96E6FA1BE5FE'  # Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>
               '474E22316ABF4785A88C6E8EA2C794A986419D8A'  # Tom Stellard <tstellar@redhat.com>
               'B6C8F98282B944E3B0D5C2530FC3042E345AD05D') # Hans Wennborg <hans@chromium.org>
-
-# hack the bootstrap
-_stage0date="2022-08-11"
-_stage0version="1.63.0"
-if [[ $_bootstrapping != "no" && $MINGW_PACKAGE_PREFIX == *-clang-aarch64 ]]; then
-  source+=("https://github.com/mati865/rust-gnullvm-builds/releases/download/${_stage0version}-v2/cargo-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz"
-           "https://github.com/mati865/rust-gnullvm-builds/releases/download/${_stage0version}-v2/rust-std-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz"
-           "https://github.com/mati865/rust-gnullvm-builds/releases/download/${_stage0version}-v2/rustc-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz")
-  noextract+=("cargo-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz"
-              "rust-std-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz"
-              "rustc-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz")
-fi
 
 # =========================================== #
 #   Helper macros to help make tasks easier   #
@@ -90,34 +97,34 @@ COMPRESSZST+=(--long)
 
 prepare() {
   plain "Extracting ${_realname}c-${pkgver}-src.tar.gz"
-  tar -xzf ${_realname}c-${pkgver}-src.tar.gz || true
+  mkdir -p ${MSYSTEM} && tar -xzf ${_realname}c-${pkgver}-src.tar.gz -C ${MSYSTEM} || true
+
+  mv cc-1.2.19 ${MSYSTEM}/${_realname}c-${pkgver}-src/vendor/cc-1.2.19
+  mv cc-1.1.10 ${MSYSTEM}/${_realname}c-${pkgver}-src/vendor/cc-1.1.10
+  # rustc-perf should be added as git repository
+  rm -rf ${MSYSTEM}/${_realname}c-${pkgver}-src/src/tools/rustc-perf
+  cp -rf rustc-perf ${MSYSTEM}/${_realname}c-${pkgver}-src/src/tools/rustc-perf
 
   # 0008-disable-self-contained-for-gnu-targets.patch allows self-contained for non-windows-gnu targets
-  cd ${_realname}c-${pkgver}-src
+  cd ${MSYSTEM}/${_realname}c-${pkgver}-src
   apply_patch_with_msg \
-    0001-rustc-llvm-fix-libs.patch \
-    0008-disable-self-contained-for-gnu-targets.patch
+    0008-disable-self-contained-for-gnu-targets.patch \
+    0004-compiler-Use-wasm-ld-for-wasm-targets.patch \
+    137676.patch \
+    139757.patch \
+    139894.patch \
+    139931.patch \
+    139962.patch
 
-  if [[ ${CARCH} != i686 ]]; then
-    apply_patch_with_msg \
-      0004-compiler-Use-wasm-ld-for-wasm-targets.patch
-  fi
+  msg2 "Applying 0012-rustc-perf-update-cc.patch"
+  patch -d src/tools/rustc-perf -p1 -i ${srcdir}/0012-rustc-perf-update-cc.patch
 
   apply_patch_with_msg \
-    0009-support-LLVM20.patch
+    0013-deps-checksums.patch
 }
 
 build() {
-  cd "${_realname}c-${pkgver}-src"
-
-  # hack to inject the bootstrap compiler
-  if [[ $_bootstrapping != "no" && $MINGW_PACKAGE_PREFIX == *-clang-aarch64 ]]; then
-    mkdir -p "build-${MSYSTEM}/cache/${_stage0date}/"
-    cp -f "${srcdir}/cargo-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz" \
-      "${srcdir}/rust-std-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz" \
-      "${srcdir}/rustc-${_stage0version}-dev-aarch64-pc-windows-gnullvm.tar.xz" \
-      "build-${MSYSTEM}/cache/${_stage0date}/"
-  fi
+  cd "${MSYSTEM}/${_realname}c-${pkgver}-src"
 
   if [[ $MINGW_PACKAGE_PREFIX == *-clang-* ]]; then
     # We have to do the following because rust doesn't count x86_64-w64-mingw32 as a target triple
@@ -125,6 +132,11 @@ build() {
   else
     # We have to do the following because rust doesn't count x86_64-w64-mingw32 as a target triple
     export OSTYPE="$CARCH-pc-windows-gnu"
+  fi
+
+  if [[ $_bootstrapping == "no" ]]; then
+    mkdir -p "build/$OSTYPE/stage0/bin"
+    cp -f "${MINGW_PREFIX}"/bin/{cargo,rustc}.exe "build/$OSTYPE/stage0/bin"
   fi
 
   if [[ $MINGW_PACKAGE_PREFIX != *-clang-aarch64 ]]; then
@@ -143,43 +155,54 @@ build() {
   # - remove --stage 2
 
   export RUST_BACKTRACE=1
+  export RUST_LOG=info
 
   # substitute the values in config.toml
   export MSYS2_ENV_CONV_EXCL='INSTALL_PREFIX'
   export INSTALL_PREFIX="${MINGW_PREFIX}"
   export PKGREL="${pkgrel}"
-  envsubst < ../config.toml > config.toml
+  envsubst < ${srcdir}/config.toml > config.toml
 
   if [ "${_bootstrapping}" = "no" ]; then
     sed -i '/^\[build\]/,/^$/ s|^#||g' config.toml
   fi
   # generate debuginfo only for non-i686 targets
-  if check_option "debug" "y" && [ "${CARCH}" != i686 ]; then
+  if check_option "debug" "y"; then
     sed -i 's/^#debug/debug/g' config.toml
   fi
 
-  # Add target wasm32-*
-  if [[ ${CARCH} != i686 ]]; then
-    sed -i -e '/target = \[/a\  "wasm32-unknown-unknown", "wasm32-wasip1", "wasm32v1-none", "wasm32-wasip1-threads", "wasm32-wasip2",' \
-           -e '/tools = \[/a\  "clippy", "rustdoc", "rustfmt", "rust-analyzer-proc-macro-srv", "analysis", "src",' config.toml
-  fi
+  # build opt-dist tool which manages PGO build
+  python x.py build opt-dist --target="$OSTYPE"
 
-  local -a _rust_build=()
-  _rust_build+=("--stage" "2")
-  #_rust_build+=("--verbose")
+  # run opt-dist to get rustc optimized with PGO. Final stage fails, so put a `echo` invocation
+  # and ignore errors
+  build/$OSTYPE/stage0-tools-bin/opt-dist local \
+    --target-triple="$OSTYPE" \
+    --checkout-dir="$PWD" \
+    --llvm-dir="${MINGW_PREFIX}" \
+    --llvm-shared=false \
+    --python="${MINGW_PREFIX}/bin/python.exe" \
+    --artifact-dir="$PWD"/opt-artifacts -- \
+    echo "Dummy message" || true
 
-  # create the install at a temporary directory
-  DESTDIR="$PWD/build-$MSYSTEM/dest-rust" python x.py install "${_rust_build[@]}"
+  plain "Running final build manually"
+  # build profiled compiler with profiled LLVM separately
+  sed -i 's/^#lto/lto/;s/^metrics/#metrics/' config.toml
+  python x.py build library/std --stage 2 \
+    --target="$OSTYPE" \
+    --llvm-profile-use "$PWD"/opt-artifacts/llvm-pgo.profdata \
+    --rust-profile-use "$PWD"/opt-artifacts/rustc-pgo.profdata \
+    --keep-stage 0
+  # comment this option to make wasm* targets buildable
+  sed -i 's/^use-lld/#use-lld/' config.toml
+  DESTDIR="$PWD"/dest-rust python x.py install --stage 2 \
+    --rust-profile-use "$PWD"/opt-artifacts/rustc-pgo.profdata \
+    --keep-stage 0 \
+    --keep-stage 1
 
-  cd build-${MSYSTEM}
-  if [[ ${CARCH} != i686 ]]; then
-    # move wasm32-* targets out of the way for splitting
-    mkdir -p dest-wasm${MINGW_PREFIX}/lib/rustlib
-    mv dest-rust${MINGW_PREFIX}/lib/rustlib/wasm32{,v1}-* dest-wasm${MINGW_PREFIX}/lib/rustlib
-    # move src out of the way for splitting
-    mkdir -p dest-src${MINGW_PREFIX}/lib/rustlib
-    mv dest-rust${MINGW_PREFIX}/lib/rustlib/src dest-src${MINGW_PREFIX}/lib/rustlib
-  fi
+  # move wasm32-* targets out of the way for splitting
+  mkdir -p dest-wasm${MINGW_PREFIX}/lib/rustlib
+  mv dest-rust${MINGW_PREFIX}/lib/rustlib/wasm32{,v1}-* dest-wasm${MINGW_PREFIX}/lib/rustlib
 
   rm -f dest-rust${MINGW_PREFIX}/lib/rustlib/$OSTYPE/lib/self-contained/*
 }
@@ -201,7 +224,7 @@ package_rust() {
   conflicts=("${MINGW_PACKAGE_PREFIX}-rust-docs")
   replaces=("${MINGW_PACKAGE_PREFIX}-rust-docs")
 
-  cd "${_realname}c-${pkgver}-src/build-${MSYSTEM}"
+  cd "${MSYSTEM}/${_realname}c-${pkgver}-src"
 
   cp -a dest-rust/* "${pkgdir}"
 
@@ -226,7 +249,7 @@ package_rust-wasm() {
   # strip wasm object files manually due to binutils' lack of support
   options=('!strip')
 
-  cd "${_realname}c-${pkgver}-src/build-${MSYSTEM}"
+  cd "${MSYSTEM}/${_realname}c-${pkgver}-src"
 
   cp -a dest-wasm/* "${pkgdir}"
 
@@ -234,17 +257,7 @@ package_rust-wasm() {
     llvm-strip --strip-debug wasm32*/lib/*.rlib
   popd
 
-  install -Dm644 ../LICENSE-{APACHE,MIT} -t "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}-wasm"
-}
-
-package_rust-src() {
-  pkgdesc='Source code for the Rust standard library (mingw-w64)'
-  depends=("${MINGW_PACKAGE_PREFIX}-rust")
-
-  cd "${_realname}c-${pkgver}-src/build-$MSYSTEM"
-
-  cp -a dest-src/* "${pkgdir}"
-  install -Dm644 ../LICENSE-{APACHE,MIT} -t "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}-src"
+  install -Dm644 LICENSE-{APACHE,MIT} -t "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}-wasm"
 }
 
 # template start; name=mingw-w64-splitpkg-wrappers; version=1.0;
