rust: fix/skip tests that fail on CLANG*
* skip debuginfo tests on all platforms

* skip tests that fail on CLANG*

* enable no-fail-fast

* checkdepends on gcc-compat package for clang

Because of the bootstrapping hack, at least one test tries to use
$TRIPLE-gcc to link rather than $TRIPLE-clang.  The easiest workaround
seems to be to ensure there is an alias to clang with that name.

diff --git a/mingw-w64-rust/PKGBUILD b/mingw-w64-rust/PKGBUILD
--- a/mingw-w64-rust/PKGBUILD
+++ b/mingw-w64-rust/PKGBUILD
@@ -44,6 +44,7 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
              "${MINGW_PACKAGE_PREFIX}-autotools"
              $([[ "$_bootstrapping" == "no" ]] && echo "${MINGW_PACKAGE_PREFIX}-rust")
              "${MINGW_PACKAGE_PREFIX}-zlib")
+checkdepends=($([[ ${MINGW_PACKAGE_PREFIX} != *-clang-* ]] || echo "${MINGW_PACKAGE_PREFIX}-gcc-compat"))
 source=("${rust_dist_server}/${_realname}c-${pkgver}-src.tar.gz"{,.asc}
         "${embed_manifest_url}"
         "https://github.com/rust-lang/rust/commit/eac0b3a1d1b8d1db8fa95c50e118de5b9471e5af.patch"
@@ -226,10 +227,25 @@ build() {
 
 check() {
   cd "${srcdir}/${MSYSTEM}"
+  local -a _extra_test_args=()
+  if [[ $MINGW_PACKAGE_PREFIX == *-clang-* ]]; then
+    # these fail for gnullvm because dlltool is not used there
+    _extra_test_args+=(
+      "--skip" "tests/ui/rfcs/rfc-2627-raw-dylib/dlltool-failed.rs"
+      "--skip" "tests/ui/rfcs/rfc-2627-raw-dylib/invalid-dlltool.rs"
+      "--skip" "tests/run-make/raw-dylib-custom-dlltool")
+    if [[ $MINGW_PACKAGE_PREFIX == *-i686 || $MINGW_PACKAGE_PREFIX == *-x86_64 ]]; then
+      # these fail because we modified the *-windows-gnu specs
+      _extra_test_args+=(
+        "--skip" "spec::tests::i686_pc_windows_gnu"
+        "--skip" "spec::tests::x86_64_pc_windows_gnu")
+    fi
+  fi
+
   DEP_NGHTTP_ROOT=${MINGW_PREFIX} \
   DEP_OPENSSL_ROOT=${MINGW_PREFIX} \
   DEP_Z_ROOT=${MINGW_PREFIX} \
-  ${MINGW_PREFIX}/bin/python ../${_realname}c-${pkgver}-src/x.py test --stage 2 --exclude src/test/debuginfo
+  ${MINGW_PREFIX}/bin/python ../${_realname}c-${pkgver}-src/x.py test --no-fail-fast --stage 2 -- --skip tests/debuginfo "${_extra_test_args[@]}"
 }
 
 package_rust() {
