nlopt: update to 2.11.0 (#29841)
* fix installation path of python binding
* clean cmake args
* fix check()

diff --git a/mingw-w64-nlopt/PKGBUILD b/mingw-w64-nlopt/PKGBUILD
--- a/mingw-w64-nlopt/PKGBUILD
+++ b/mingw-w64-nlopt/PKGBUILD
@@ -1,10 +1,11 @@
 # Maintainer: Ray Donnelly <mingw.android@gmail.com>
+# Contributor: dragon-archer <dragon-archer@outlook.com>
 
 _realname=nlopt
 pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
-pkgver=2.10.1
-pkgrel=3
+pkgver=2.11.0
+pkgrel=1
 pkgdesc="A library for nonlinear optimization (mingw-w64)"
 arch=('any')
 mingw_arch=('mingw64' 'ucrt64' 'clang64' 'clangarm64')
@@ -19,9 +20,11 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
              "${MINGW_PACKAGE_PREFIX}-python-numpy"
              "${MINGW_PACKAGE_PREFIX}-swig")
 source=("https://github.com/stevengj/nlopt/archive/v${pkgver}/${_realname}-${pkgver}.tar.gz"
-        "0001-avoid-hardcoded-lib-path.patch")
-sha256sums=('30d13ce16da119db3e987784f7864e35a562ec62c186352fae55cd003e6c58ff'
-            '8301f83c47f26b1429dd5b283d89f088bfbdf9ca42146f2b3e62e0a6487a67e1')
+        "0001-fix-lib-path.patch"
+        "0002-fix-test-path.patch")
+sha256sums=('53e552d83e9294d67db37f0f4a23f15933a9ef698485301a18b98b40004cf0de'
+            '56a6967c0dc69ff8d58f6785e88105751553dc95e96e9fc472731ac6e58dd9ae'
+            '5ed7c912cfa4ee48dd5e5bdd4d90c66f1519c1f07d5cf77a49e79d5f419ffacd')
 noextract=(${_realname}-${pkgver}.tar.gz)
 
 prepare () {
@@ -30,36 +33,40 @@ prepare () {
 
   cd "${_realname}-${pkgver}"
 
-  patch -p1 -i "${srcdir}"/0001-avoid-hardcoded-lib-path.patch
+  patch -Nbp1 -i "${srcdir}"/0001-fix-lib-path.patch
+  patch -Nbp1 -i "${srcdir}"/0002-fix-test-path.patch
 }
 
 build() {
-  mkdir -p "${srcdir}"/build-${MSYSTEM} && cd "${srcdir}"/build-${MSYSTEM}
+  declare -a extra_config
+  if check_option "debug" "n"; then
+    extra_config+=("-DCMAKE_BUILD_TYPE=Release")
+  else
+    extra_config+=("-DCMAKE_BUILD_TYPE=Debug")
+  fi
 
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
-  "${MINGW_PREFIX}/bin/cmake.exe" \
-    -Wno-dev \
-    -G"Ninja" \
-    -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" \
-    -DPython_EXECUTABLE="${MINGW_PREFIX}/bin/python" \
-    -DBUILD_SHARED_LIBS=ON \
-    -DNLOPT_JAVA=OFF \
-    -DNLOPT_PYTHON=ON \
-    -DNLOPT_SWIG=ON \
-    -DNLOPT_GUILE=OFF \
-    ../${_realname}-${pkgver}
+    cmake \
+      -GNinja \
+      -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" \
+      -DPython_EXECUTABLE="${MINGW_PREFIX}/bin/python.exe" \
+      -DNLOPT_JAVA=OFF \
+      -DNLOPT_GUILE=OFF \
+      "${_extra_config[@]}" \
+      -S ${_realname}-${pkgver} \
+      -B build-${MSYSTEM}
 
-  ${MINGW_PREFIX}/bin/cmake.exe --build ./
+  cmake --build build-${MSYSTEM}
 }
 
 check() {
-  cd "${srcdir}"/build-${MSYSTEM}
-
-  # DLLs from gcc-libs need to be copied to test folder
-  ${MINGW_PREFIX}/bin/ctest.exe ./ || true
+  cmake -DNLOPT_TESTS=ON -S ${_realname}-${pkgver} -B build-${MSYSTEM}
+  cmake --build build-${MSYSTEM}
+  cp build-${MSYSTEM}/libnlopt.dll build-${MSYSTEM}/test/
+  # Python tests failed to load _nlopt without installing
+  ctest --test-dir build-${MSYSTEM} --output-on-failure || true
 }
 
 package() {
-  cd "${srcdir}"/build-${MSYSTEM}
-  DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/cmake.exe --install ./
+  DESTDIR="${pkgdir}" cmake --install build-${MSYSTEM}
 }
