vtk: rebuild dependent packages

diff --git a/mingw-w64-opencascade/PKGBUILD b/mingw-w64-opencascade/PKGBUILD
--- a/mingw-w64-opencascade/PKGBUILD
+++ b/mingw-w64-opencascade/PKGBUILD
@@ -5,7 +5,7 @@ pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
 pkgver=7.7.0
 _pkgver2=V${pkgver//./_}
-pkgrel=7
+pkgrel=8
 pkgdesc='Open CASCADE Technology, 3D modeling & numerical simulation (mingw-w64)'
 arch=('any')
 mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32' 'clangarm64')
@@ -17,7 +17,7 @@ depends=("${MINGW_PACKAGE_PREFIX}-ffmpeg4.4"
          "${MINGW_PACKAGE_PREFIX}-rapidjson"
          "${MINGW_PACKAGE_PREFIX}-tcl"
          "${MINGW_PACKAGE_PREFIX}-tk"
-         "${MINGW_PACKAGE_PREFIX}-vtk")
+         $([[ ${CARCH} == i686 ]] || echo "${MINGW_PACKAGE_PREFIX}-vtk"))
 makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
              "${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-ninja"
@@ -154,11 +154,16 @@ build() {
     -D3RDPARTY_TBBMALLOC_DLL="${MINGW_PREFIX}/bin/libtbbmalloc.dll"
     -D3RDPARTY_TBBMALLOC_LIBRARY_DIR="${MINGW_PREFIX}/lib/"
     -D3RDPARTY_TBBMALLOC_LIBRARY="${MINGW_PREFIX}/lib/libtbbmalloc.dll.a"
-    -DUSE_VTK=1
-    -D3RDPARTY_VTK_DLL_DIR="${MINGW_PREFIX}/bin/"
-    -D3RDPARTY_VTK_LIBRARY_DIR="${MINGW_PREFIX}/lib/"
-    -D3RDPARTY_VTK_INCLUDE_DIR="${MINGW_PREFIX}/include/vtk"
   )
+
+  if [[ ${CARCH} != i686 ]]; then
+    common_config+=(
+      -DUSE_VTK=ON
+      -D3RDPARTY_VTK_DLL_DIR="${MINGW_PREFIX}/bin/"
+      -D3RDPARTY_VTK_LIBRARY_DIR="${MINGW_PREFIX}/lib/"
+      -D3RDPARTY_VTK_INCLUDE_DIR="${MINGW_PREFIX}/include/vtk"
+    )
+  fi
 
   if [[ ${MINGW_PACKAGE_PREFIX} == *-clang-i686 ]]; then
     common_config+=(
@@ -173,34 +178,35 @@ build() {
     _extra_config+=("-DCMAKE_BUILD_TYPE=Debug")
   fi
 
-  if [[ "${MSYSTEM}" == "MINGW64" ]]; then
+  # Building static libraries fails with VTK 9.3.0
+  # if [[ "${MSYSTEM}" == "MINGW64" ]]; then
 
-  msg2 "Building static libraries"
-  mkdir -p "${srcdir}/build-${MSYSTEM}-static" && cd "${srcdir}/build-${MSYSTEM}-static"
+  # msg2 "Building static libraries"
+  # mkdir -p "${srcdir}/build-${MSYSTEM}-static" && cd "${srcdir}/build-${MSYSTEM}-static"
 
-  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
-  ${MINGW_PREFIX}/bin/cmake -Wno-dev \
-    -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
-    -GNinja \
-    "${_extra_config[@]}" \
-    -DINSTALL_DIR_LAYOUT="Unix" \
-    -DBUILD_LIBRARY_TYPE="Static" \
-    "${common_config[@]}" \
-    -D3RDPARTY_TK_LIBRARY="${MINGW_PREFIX}/lib/libtk86.a" \
-    -D3RDPARTY_TCL_LIBRARY="${MINGW_PREFIX}/lib/libtcl86.a" \
-    -D3RDPARTY_FREETYPE_LIBRARY="${MINGW_PREFIX}/lib/libfreetype.a" \
-    -D3RDPARTY_FFMPEG_LIBRARY_avformat="${MINGW_PREFIX}/lib/ffmpeg4.4/libavformat.a" \
-    -D3RDPARTY_FFMPEG_LIBRARY_avutil="${MINGW_PREFIX}/lib/ffmpeg4.4/libavutil.a" \
-    -D3RDPARTY_FFMPEG_LIBRARY_avcodec="${MINGW_PREFIX}/lib/ffmpeg4.4/libavcodec.a" \
-    -D3RDPARTY_FFMPEG_LIBRARY_swscale="${MINGW_PREFIX}/lib/ffmpeg4.4/libswscale.a" \
-    -D3RDPARTY_FREEIMAGE_LIBRARY="${MINGW_PREFIX}/lib/libfreeimage.a" \
-    -D3RDPARTY_OPENVR_LIBRARY_openvr_api="${MINGW_PREFIX}/lib/libopenvr_api.a" \
-    -DOPENVDB_USE_STATIC_LIBS=ON \
-    ../occt-${_pkgver2}
+  # MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
+  # ${MINGW_PREFIX}/bin/cmake -Wno-dev \
+  #   -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
+  #   -GNinja \
+  #   "${_extra_config[@]}" \
+  #   -DINSTALL_DIR_LAYOUT="Unix" \
+  #   -DBUILD_LIBRARY_TYPE="Static" \
+  #   "${common_config[@]}" \
+  #   -D3RDPARTY_TK_LIBRARY="${MINGW_PREFIX}/lib/libtk86.a" \
+  #   -D3RDPARTY_TCL_LIBRARY="${MINGW_PREFIX}/lib/libtcl86.a" \
+  #   -D3RDPARTY_FREETYPE_LIBRARY="${MINGW_PREFIX}/lib/libfreetype.a" \
+  #   -D3RDPARTY_FFMPEG_LIBRARY_avformat="${MINGW_PREFIX}/lib/ffmpeg4.4/libavformat.a" \
+  #   -D3RDPARTY_FFMPEG_LIBRARY_avutil="${MINGW_PREFIX}/lib/ffmpeg4.4/libavutil.a" \
+  #   -D3RDPARTY_FFMPEG_LIBRARY_avcodec="${MINGW_PREFIX}/lib/ffmpeg4.4/libavcodec.a" \
+  #   -D3RDPARTY_FFMPEG_LIBRARY_swscale="${MINGW_PREFIX}/lib/ffmpeg4.4/libswscale.a" \
+  #   -D3RDPARTY_FREEIMAGE_LIBRARY="${MINGW_PREFIX}/lib/libfreeimage.a" \
+  #   -D3RDPARTY_OPENVR_LIBRARY_openvr_api="${MINGW_PREFIX}/lib/libopenvr_api.a" \
+  #   -DOPENVDB_USE_STATIC_LIBS=ON \
+  #   ../occt-${_pkgver2}
 
-  ${MINGW_PREFIX}/bin/cmake --build .
+  # ${MINGW_PREFIX}/bin/cmake --build .
 
-  fi
+  # fi
 
   mkdir -p "${srcdir}/build-${MSYSTEM}-shared" && cd "${srcdir}/build-${MSYSTEM}-shared"
 
@@ -227,11 +233,11 @@ build() {
 }
 
 package() {
-  if [[ "${MSYSTEM}" == "MINGW64" ]]; then
-    # Static Install
-    cd "${srcdir}/build-${MSYSTEM}-static"
-    DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/cmake --install .
-  fi
+  # if [[ "${MSYSTEM}" == "MINGW64" ]]; then
+  #   # Static Install
+  #   cd "${srcdir}/build-${MSYSTEM}-static"
+  #   DESTDIR="${pkgdir}" ${MINGW_PREFIX}/bin/cmake --install .
+  # fi
 
   # Shared Install
   cd "${srcdir}/build-${MSYSTEM}-shared"
