clang + clang-svn: Added lldb (disabled as WIP)

diff --git a/mingw-w64-clang/PKGBUILD b/mingw-w64-clang/PKGBUILD
--- a/mingw-w64-clang/PKGBUILD
+++ b/mingw-w64-clang/PKGBUILD
@@ -11,12 +11,12 @@ pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
          "${MINGW_PACKAGE_PREFIX}-libc++abi"
          "${MINGW_PACKAGE_PREFIX}-libc++"
          "${MINGW_PACKAGE_PREFIX}-lld"
-         #"${MINGW_PACKAGE_PREFIX}-lldb"
          "${MINGW_PACKAGE_PREFIX}-llvm"
+         #"${MINGW_PACKAGE_PREFIX}-lldb"
          )
 pkgver=3.7.0
-pkgrel=9
-pkgdesc="LC language family frontend for LLVM (mingw-w64)"
+pkgrel=10
+pkgdesc="C language family frontend for LLVM (mingw-w64)"
 arch=('any')
 url="http://llvm.org"
 license=("custom:University of Illinois/NCSA Open Source License")
@@ -25,9 +25,12 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-cmake"
              "${MINGW_PACKAGE_PREFIX}-libffi"
              "${MINGW_PACKAGE_PREFIX}-pkg-config"
              "${MINGW_PACKAGE_PREFIX}-python3-sphinx"
-             "python2" "tar" "groff")
+             "${MINGW_PACKAGE_PREFIX}-python2"
+             "tar"
+             "groff")
 depends=("${MINGW_PACKAGE_PREFIX}-gcc")
-options=('staticlibs' 'strip')
+#options=('debug' '!strip')
+validpgpkeys=('B6C8F98282B944E3B0D5C2530FC3042E345AD05D') # Hans Wennborg, Google.
 source=(http://llvm.org/releases/${pkgver}/llvm-${pkgver}.src.tar.xz{,.sig}
         http://llvm.org/releases/${pkgver}/cfe-${pkgver}.src.tar.xz{,.sig}
         http://llvm.org/releases/${pkgver}/compiler-rt-${pkgver}.src.tar.xz{,.sig}
@@ -36,6 +39,7 @@ source=(http://llvm.org/releases/${pkgver}/llvm-${pkgver}.src.tar.xz{,.sig}
         http://llvm.org/releases/${pkgver}/libcxxabi-${pkgver}.src.tar.xz{,.sig}
         http://llvm.org/releases/${pkgver}/clang-tools-extra-${pkgver}.src.tar.xz{,.sig}
         http://llvm.org/releases/${pkgver}/lld-${pkgver}.src.tar.xz{,.sig}
+        http://llvm.org/releases/${pkgver}/lldb-${pkgver}.src.tar.xz{,.sig}
         0001-Fix-GetHostTriple-for-mingw-w64-in-msys.patch
         0002-use-DESTDIR-on-windows.patch
         0003-generate-proper-library-names-mingw.patch
@@ -59,6 +63,7 @@ source=(http://llvm.org/releases/${pkgver}/llvm-${pkgver}.src.tar.xz{,.sig}
 #0021-0029 -> rt
 #0031-0039 -> lld
 #0041-0049 -> c++
+#0051-0059 -> lldb
 
 sha256sums=('ab45895f9dcdad1e140a3a79fd709f64b05ad7364e308c0e582c5b02e9cc3153'
             'SKIP'
@@ -76,6 +81,8 @@ sha256sums=('ab45895f9dcdad1e140a3a79fd709f64b05ad7364e308c0e582c5b02e9cc3153'
             'SKIP'
             'ddb658b789c501efbe4f54ff8ced2c07cd9ff686c92445d8a1ab2cd5dbd837ed'
             'SKIP'
+            'f4d7505bc111044eaa4033af012221e492938405b62522b8e3e354c20c4b71e9'
+            'SKIP'
             '0804146b32138d55c611336cc81e1783c29a8fab0fe62f248ba1ad7acc711c4d'
             'bf22d86c0546b80cd7212b7e7c3e1b628f00ab3aa3b9cf73ad338bf628f42597'
             '6a95ed671876a6de04799d15bf7485d628016bb4a95a6764217ad452d8eed0d8'
@@ -83,7 +90,7 @@ sha256sums=('ab45895f9dcdad1e140a3a79fd709f64b05ad7364e308c0e582c5b02e9cc3153'
             '8f35b80eca6c18df020b176eee4eb95901c31e3e640848a6d606983aca15a3af'
             '962b4de1afa781ee171f71211518c58f6a3531d7fcca5ec458e39703b0fb9af7'
             'f7bc109b07b5256a068dbe55097c24b46307aea442bec884d8ba455dc3ad18fd'
-            '59e7afa5e74d186ad596c9a7625d6022fde0679faea9d1fd516fe0a622dbc01a'
+            'e0f4127df5857af667a9e40e2a7a13877352b89c99f3213b491215bf7bd03565'
             '47fbe90718742d1a3c0aee919b159241e616738447de3505a48a9f5886e5db96'
             '0e45e76ee6d6658de52edb7b508a8bcc9f10ff0b295ff2a4e35577136a40c6a5'
             '421befbe54123066544f53876c7eb6013ac6684744d8173fb0a3fa9be16d68c7'
@@ -127,16 +134,6 @@ prepare() {
   cd "${srcdir}/libcxx-${pkgver}.src"
   patch -p1 -i "${srcdir}"/0041-libcxx-add-support-for-mingw-w64.patch
 
-  cd "${srcdir}"
-  mv lld-${pkgver}.src               llvm-${pkgver}.src/tools/lld
-  mv cfe-${pkgver}.src                llvm-${pkgver}.src/tools/clang
-  mv clang-tools-extra-${pkgver}.src  llvm-${pkgver}.src/tools/clang/tools/extra
-  mv compiler-rt-${pkgver}.src        llvm-${pkgver}.src/projects/compiler-rt
-  mv libcxxabi-${pkgver}.src          llvm-${pkgver}.src/projects/libcxxabi
-  mv libcxx-${pkgver}.src             llvm-${pkgver}.src/projects/libcxx
-  # mv testsuite-${pkgver}.src         llvm-${pkgver}.src/projects/test-suite
-
-
   cd "${srcdir}/llvm-${pkgver}.src"
 
   # Fix docs installation directory
@@ -146,22 +143,48 @@ prepare() {
   # Fix definition of LLVM_CMAKE_DIR in LLVMConfig.cmake
   sed -i '/@LLVM_CONFIG_CMAKE_DIR@/s:$(PROJ_cmake):$(PROJ_prefix)/share/llvm/cmake:' \
     cmake/modules/Makefile
+  cd "${srcdir}"/llvm-${pkgver}.src
+
+  # At the present, clang must reside inside the LLVM source code tree to build
+  # See http://llvm.org/bugs/show_bug.cgi?id=4840
+
+  mv "${srcdir}/cfe-${pkgver}.src"               tools/clang
+  mv "${srcdir}/clang-tools-extra-${pkgver}.src" tools/clang/tools/extra
+  mv "${srcdir}/lld-${pkgver}.src"               tools/lld
+  mv "${srcdir}/lldb-${pkgver}.src"              tools/lldb
+  mv "${srcdir}/compiler-rt-${pkgver}.src"       projects/compiler-rt
+  mv "${srcdir}/libcxxabi-${pkgver}.src"         projects/libcxxabi
+  mv "${srcdir}/libcxx-${pkgver}.src"            projects/libcxx
+# mv "${srcdir}/testsuite-${pkgver}.src"         projects/test-suite
 }
 
 build() {
-  mkdir -p ${srcdir}/build-${CARCH} && cd ${srcdir}/build-${CARCH}
+  cd "${srcdir}"
+
+  [[ -d build-${CARCH} ]] && rm -rf build-${CARCH}
+  mkdir build-${CARCH} && cd build-${CARCH}
+
+  local -a extra_config
+
+  if check_option "debug" "y"; then
+    extra_config+=(-DCMAKE_BUILD_TYPE=Debug)
+    VERBOSE="VERBOSE=1"
+  else
+    extra_config+=(-DCMAKE_BUILD_TYPE=Release)
+  fi
 
   # Include location of libffi headers in CPPFLAGS
-  #CPPFLAGS+="$(pkg-config --cflags libffi)"
   FFI_INCLUDE_DIR="$(pkg-config --cflags libffi)"
   FFI_INCLUDE_DIR=$(echo $FFI_INCLUDE_DIR | sed 's|-I||g')
 
   # "Ninja" cant install each component seperately
   # https://github.com/martine/ninja/issues/932
 
+  PATH=${MINGW_PREFIX}/bin:/usr/bin \
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
   ${MINGW_PREFIX}/bin/cmake.exe \
     -G"MSYS Makefiles" \
+    -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib \
     -DCMAKE_MAKE_PROGRAM="/usr/bin/make.exe" \
     -DCMAKE_C_COMPILER="${MINGW_PREFIX}/bin/gcc.exe" \
     -DCMAKE_CXX_COMPILER="${MINGW_PREFIX}/bin/g++.exe" \
@@ -169,9 +192,9 @@ build() {
     -DCMAKE_C_FLAGS="${CFLAGS}" \
     -DCMAKE_CXX_FLAGS="${CXXFLAGS} ${CPPFLAGS}" \
     -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
-    -DCMAKE_BUILD_TYPE=Release \
     -DLLVM_TARGETS_TO_BUILD="ARM;CppBackend;X86" \
     -DLLVM_ENABLE_ASSERTIONS=OFF \
+    -DLLVM_ENABLE_THREADS=1 \
     -DPYTHON_EXECUTABLE=${MINGW_PREFIX}/bin/python2.exe \
     -DLLVM_ENABLE_FFI=ON \
     -DLLVM_ENABLE_SPHINX=ON \
@@ -179,59 +202,117 @@ build() {
     -DLIBCLANG_BUILD_STATIC=ON \
     -DLIBCXX_ENABLE_SHARED=OFF \
     -DLIBCXXABI_ENABLE_SHARED=OFF \
+    "${extra_config[@]}" \
     ../llvm-${pkgver}.src
 
-  make
+  make ${VERBOSE}
 
   # Disable automatic installation of components that go into subpackages
-  cp tools/cmake_install.cmake tools/cmake_install.cmake.orig
-  cp tools/clang/tools/cmake_install.cmake tools/clang/tools/cmake_install.cmake.orig
-  cp projects/cmake_install.cmake projects/cmake_install.cmake.orig
-  
-  sed -i '/\(clang\|lld\|lldb\)\/cmake_install.cmake/d' tools/cmake_install.cmake
-  sed -i '/\(extra\|scan-build\|scan-view\)\/cmake_install.cmake/d' tools/clang/tools/cmake_install.cmake
-  sed -i '/\(compiler-rt\|libcxxabi\|libcxx\)\/cmake_install.cmake/d' projects/cmake_install.cmake
+  # -i.orig to check what has been removed in-case it starts dropping more than it should
+  #
+  sed -i.orig '/\(clang\|lld\|lldb\)\/cmake_install.cmake/d' tools/cmake_install.cmake
+  sed -i.orig '/\(extra\|scan-build\|scan-view\)\/cmake_install.cmake/d' tools/clang/tools/cmake_install.cmake
+  sed -i.orig '/\(compiler-rt\|libcxxabi\|libcxx\)\/cmake_install.cmake/d' projects/cmake_install.cmake
 }
 
-check() {
-  plain "skipping make check..."
-  #cd "${srcdir}/build-${MINGW_CHOST}"
-  #make check
+#check() {
+#  cd "${srcdir}"/build-${CARCH}
+#  # Remove || true once testcase doesn't cause failures.
+#  make check || true
+#}
+
+package_llvm() {
+  pkgdesc="Low Level Virtual Machine (mingw-w64)"
+  #depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs") # "compiler-rt"
+  install=llvm-${CARCH}.install
+
+  cd "${srcdir}"/llvm-${pkgver}.src
+
+  make -C ../build-${CARCH} DESTDIR="${pkgdir}" install
+
+  install -Dm644 LICENSE.TXT "${pkgdir}${MINGW_PREFIX}/share/licenses/llvm/LICENSE"
+
+  # Install CMake stuff
+  install -d "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/{modules,platforms}
+  install -Dm644 "${srcdir}"/llvm/cmake/modules/*.cmake "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/modules/
+  install -Dm644 "${srcdir}"/llvm/cmake/platforms/*.cmake "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/platforms/
+
+  # FileCheck is needed to build rust.
+  install -Dm755 "${srcdir}"/build-${CARCH}/bin/FileCheck.exe "${pkgdir}${MINGW_PREFIX}/bin/FileCheck.exe"
 }
 
-package_clang(){
-  pkgdesc="C language family frontend for LLVM"
+package_compiler-rt() {
+  pkgdesc="Runtime libraries for Clang and LLVM (mingw-w64)"
+  url="http://compiler-rt.llvm.org/"
   depends=("${MINGW_PACKAGE_PREFIX}-llvm=${pkgver}-${pkgrel}")
 
   cd "${srcdir}"/llvm-${pkgver}.src
+  make -C ../build-${CARCH}/projects/compiler-rt DESTDIR="${pkgdir}" install
+ }
+
+package_libcxxabi() {
+  pkgdesc="C++ Standard Library Support (mingw-w64)"
+  url="http://libcxxabi.llvm.org/"
+
+  cd "${srcdir}/llvm-${pkgver}.src"
+  make -C ../build-${CARCH}/projects/libcxxabi -j1 DESTDIR="${pkgdir}" install
+}
+
+package_libcxx() {
+  pkgdesc="C++ Standard Library (mingw-w64)"
+  url="http://libcxx.llvm.org/"
+
+  cd "${srcdir}/llvm-${pkgver}.src"
+  make -C ../build-${CARCH}/projects/libcxx -j1 DESTDIR="${pkgdir}" install
+}
+
+package_lldb() {
+  pkgdesc="Next generation, high-performance debugger (mingw-w64)"
+  url="http://lldb.llvm.org/"
+  depends=("${MINGW_PACKAGE_PREFIX}-readline"
+           "${MINGW_PACKAGE_PREFIX}-libxml2"
+           "${MINGW_PACKAGE_PREFIX}-python2")
+
+  cd "${srcdir}/llvm-${pkgver}.src"
+
+  make -C ../build-${CARCH}/tools/lldb DESTDIR="${pkgdir}" install
+
+  # Compile Python scripts
+  python2 -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python2.7/site-packages/lldb"
+  python2 -O -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python2.7/site-packages/lldb"
+
+  install -Dm644 tools/lldb/LICENSE.TXT "${pkgdir}${MINGW_PREFIX}/share/licenses/$pkgname/LICENSE"
+}
+
+package_lld() {
+  pkgdesc="Linker tools for LLVM (mingw-w64)"
+  url="http://lld.llvm.org/"
+
+  cd "${srcdir}/llvm-${pkgver}.src"
+  make -C ../build-${CARCH}/tools/lld -j1 DESTDIR="${pkgdir}" install
+}
+
+package_clang() {
+  pkgdesc="C language family frontend for LLVM (mingw-w64)"
+  url="http://clang.llvm.org/"
+  depends=("${MINGW_PACKAGE_PREFIX}-llvm=${pkgver}-${pkgrel}")
+
+  cd "${srcdir}/llvm-${pkgver}.src"
   make -C ../build-${CARCH}/tools/clang DESTDIR="${pkgdir}" install
-  
-  cp -f ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/
+
+  # Install static clang library ..
+  cp ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/
 }
 
 package_clang-analyzer() {
   pkgdesc="A source code analysis framework (mingw-w64)"
   url="http://clang-analyzer.llvm.org/"
-  depends=("${MINGW_PACKAGE_PREFIX}-clang=${pkgver}-${pkgrel}" "${MINGW_PACKAGE_PREFIX}-python2")
+  depends=("${MINGW_PACKAGE_PREFIX}-clang=${pkgver}-${pkgrel}"
+           "${MINGW_PACKAGE_PREFIX}-python2")
 
-  #cd "${srcdir}/llvm-${pkgver}.src"
-  #make -C ../build-${CARCH}/tools/clang/tools/scan-build -j1 DESTDIR="$pkgdir" install
-  #make -C ../build-${CARCH}/tools/clang/tools/scan-view -j1 DESTDIR="$pkgdir" install
-  cd "${srcdir}/llvm-${pkgver}.src/tools/clang"
-  install -d "${pkgdir}"${MINGW_PREFIX}/{bin,lib/clang-analyzer}
-  for _tool in scan-{build,view}; do
-    cp -r tools/${_tool} "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer/
-    ln -s "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer/${_tool}/${_tool} "${pkgdir}"${MINGW_PREFIX}/bin/
-  done
-
-  # scan-build looks for clang within the same directory
-  install -d "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer/scan-build/
-  ln -s "${srcdir}"/build-${CARCH}/bin/clang.exe "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer/scan-build/
-
-  # Relocate man page
-  install -d "${pkgdir}"${MINGW_PREFIX}/share/man/man1
-  mv "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer/scan-build/scan-build.1 \
-     "${pkgdir}"${MINGW_PREFIX}/share/man/man1/
+  cd "${srcdir}/llvm-${pkgver}.src"
+  make -C ../build-${CARCH}/tools/clang/tools/scan-build -j1 DESTDIR="${pkgdir}" install
+  make -C ../build-${CARCH}/tools/clang/tools/scan-view -j1 DESTDIR="${pkgdir}" install
 
   # Use Python 2
   sed -i \
@@ -240,87 +321,20 @@ package_clang-analyzer() {
     "${pkgdir}"${MINGW_PREFIX}/bin/scan-view
 
   # Compile Python scripts
-  #python2 -m compileall "${pkgdir}"${MINGW_PREFIX}/bin/clang-analyzer
+  python2 -m compileall "${pkgdir}"${MINGW_PREFIX}/bin/clang-analyzer
   python2 -O -m compileall "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer
   install -Dm644 LICENSE.TXT "${pkgdir}"${MINGW_PREFIX}/share/licenses/clang-analyzer/LICENSE
 }
 
 package_clang-tools-extra() {
-  pkgdesc="Extra tools built using Clang's tooling APIs"
+  pkgdesc="Extra tools built using Clang's tooling APIs (mingw-w64)"
   url="http://clang.llvm.org/"
-  depends=("${MINGW_PACKAGE_PREFIX}-clang=${pkgver}-${pkgrel}")
 
-  cd "$srcdir"/llvm-${pkgver}.src
-  make -C ../build-${CARCH}/tools/clang/tools/extra -j1 DESTDIR="$pkgdir" install
+  cd "${srcdir}/llvm-${pkgver}.src"
+  make -C ../build-${CARCH}/tools/clang/tools/extra -j1 DESTDIR="${pkgdir}" install
 }
 
-package_compiler-rt(){
-  pkgdesc="Runtime libraries for Clang and LLVM (mingw-w64)"
-  url="http://compiler-rt.llvm.org/"
-  depends=("${MINGW_PACKAGE_PREFIX}-llvm=${pkgver}-${pkgrel}")
-
-  cd "$srcdir"/llvm-${pkgver}.src
-  make -C ../build-${CARCH}/projects/compiler-rt DESTDIR="$pkgdir" install
-}
-
-package_libcxxabi(){
-  pkgdesc="C++ Standard Library Support (mingw-w64)"
-
-  cd "$srcdir"/llvm-${pkgver}.src
-  make -C ../build-${CARCH}/projects/libcxxabi -j1 DESTDIR="$pkgdir" install
-}
-
-package_libcxx(){
-  pkgdesc="C++ Standard Library (mingw-w64)"
-
-  cd "$srcdir"/llvm-${pkgver}.src
-  make -C ../build-${CARCH}/projects/libcxx -j1 DESTDIR="$pkgdir" install
-}
-
-package_lld(){
-  pkgdesc="Linker tools for LLVM (mingw-w64)"
-  depends=("${MINGW_PACKAGE_PREFIX}-llvm=${pkgver}-${pkgrel}")
-
-  cd "$srcdir"/llvm-${pkgver}.src
-  make -C ../build-${CARCH}/tools/lld -j1 DESTDIR="${pkgdir}" install
-}
-
-package_lldb() {
-  pkgdesc="Next generation, high-performance debugger (mingw-w64)"
-  url="http://lldb.llvm.org/"
-  depends=('libedit' 'libxml2' 'python2')
-
-  cd "$srcdir"/llvm-${pkgver}.src
-
-  make -C ../build-${CARCH}/tools/lldb DESTDIR="$pkgdir" install
-
-  # Compile Python scripts
-  python2 -m compileall "$pkgdir${MINGW_PREFIX}/lib/python2.7/site-packages/lldb"
-  python2 -O -m compileall "$pkgdir${MINGW_PREFIX}/lib/python2.7/site-packages/lldb"
-
-  install -Dm644 tools/lldb/LICENSE.TXT "$pkgdir${MINGW_PREFIX}/share/licenses/$pkgname/LICENSE"
-}
-
-package_llvm(){
-  pkgdesc="Low Level Virtual Machine (mingw-w64)"
-  #depends=("${MINGW_PACKAGE_PREFIX}-gcc") # "${MINGW_PACKAGE_PREFIX}-compiler-rt"
-  install=llvm-${CARCH}.install
-
-  cd ${srcdir}/llvm-${pkgver}.src
-  make -C ../build-${CARCH} DESTDIR="$pkgdir" install
-
-  install -Dm644 LICENSE.TXT "${pkgdir}${MINGW_PREFIX}/share/licenses/llvm/LICENSE"
-
-  # Install CMake stuff
-  install -d     "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/{modules,platforms}
-  install -Dm644 "${srcdir}"/llvm-${pkgver}.src/cmake/modules/*.cmake            "${pkgdir}${MINGW_PREFIX}/share/llvm/cmake/modules/"
-  install -Dm644 "${srcdir}"/llvm-${pkgver}.src/cmake/platforms/*.cmake          "${pkgdir}${MINGW_PREFIX}/share/llvm/cmake/platforms/"
-  install -Dm644 "${srcdir}"/build-${CARCH}/share/llvm/cmake/LLVMConfig.cmake    "${pkgdir}${MINGW_PREFIX}/share/llvm/cmake/LLVMConfig.cmake"
-
-  # Building rust needs this
-  install -Dm755 "${srcdir}"/build-${CARCH}/bin/FileCheck.exe                    "${pkgdir}${MINGW_PREFIX}/bin/FileCheck.exe"
-}
-
+# Wrappers
 package_mingw-w64-i686-clang(){
   package_clang
 }
@@ -347,6 +361,10 @@ package_mingw-w64-i686-libc++(){
 
 package_mingw-w64-i686-lld(){
   package_lld
+}
+
+package_mingw-w64-i686-lldb(){
+  package_lldb
 }
 
 package_mingw-w64-i686-llvm(){
@@ -381,6 +399,12 @@ package_mingw-w64-x86_64-lld(){
   package_lld
 }
 
+package_mingw-w64-x86_64-lldb(){
+  package_lldb
+}
+
 package_mingw-w64-x86_64-llvm(){
   package_llvm
 }
+
+# vim:set ts=2 sw=2 et:
